Add NeMo 2.0 section to the readme
NVIDIA/NeMo pull request #10646
Opened 2024-09-26 22:59 UTC by ashors1

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-09-27 17:53 UTC, jgerh commented
Completed technical edit of NeMo 2.0 updates to ReadMe. LGTM.

2024-09-27 19:37 UTC, ericharper requested changes
Blocking temporarily, I think we should get feedback from @shashank3959 before merging.

2024-09-27 22:13 UTC, shashank3959 commented on README.md
> +> NeMo 2.0 is currently supported by the LLM and VLM collections.
We have not defined VLMs so far. Good to dis-abbreviate.

2024-09-27 22:29 UTC, shashank3959 commented on README.md
> +- **Training Throughput** - NeMo 2.0 efficiently handles large-scale models and datasets. It manages large batch sizes and sequence lengths, distributing model components across GPUs through model pa
This isn't new with NeMo 2.0 right? Previous versions of NeMo could claim this capability too

2024-09-27 22:33 UTC, shashank3959 commented on README.md
> +
In the Nemo Launcher section below, we should add a one liner clarification that NeMo-run is the recommended path forward for launching and managing experiments with NeMo 2.0

2024-09-27 22:37 UTC, shashank3959 commented on README.md
> +
Can we add that NeMo-run helps configure, execute and manage experiments.

2024-09-27 22:38 UTC, shashank3959 commented on README.md
> +- For more information about NeMo 2.0, see the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/nemo-2.0/index.html).
Recommend linking directly to quick start assets as well: https://docs.nvidia.com/nemo-framework/user-guide/latest/nemo-2.0/quickstart.html

2024-09-27 22:39 UTC, shashank3959 commented on README.md
> +- For more information about NeMo 2.0, see the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/nemo-2.0/index.html).
Infact, Quickstart should be the very first bullet. More information, migration etc. should be after that.

2024-09-27 22:50 UTC, shashank3959 commented on README.md
> +- For more information about NeMo 2.0, see the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/nemo-2.0/index.html).
Second bullet could be the recipes folder we have: 
"[NeMo 2.0 Recipes](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/recipes) contains additional examples of launching large-scale runs using NeMo 2.0 and NeMo-Run."

2024-10-02 05:53 UTC, ericharper approved these changes
LGTM. Thanks!

2024-10-02 05:53 UTC, merged