[Draft] Add flux inference pipeline
NVIDIA/NeMo pull request #10752
Opened 2024-10-04 00:16 UTC by Victor49152

# What does this PR do ?

Add flux inference pipeline

**Collection**: 
diffusion

# Changelog 
/nemo/collections/diffusion

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

2024-10-04 00:19 UTC, Victor49152 commented
This PR is dependent on implementation of media in Mcore. Will need to add the changes to NeMo first or stay as a draft until the Mcore change is merged.

2024-10-04 18:16 UTC, ethanhe42 commented
@zpx01 can you take a look at the flow matching?

2024-10-04 21:21 UTC, ethanhe42 commented on nemo/collections/diffusion/vae/autoencoder.py
is this vae general or specific to flux? maybe a subfolder if it's specific? Also is there things we can reuse from huggingface diffusers?

2024-10-17 06:21 UTC, ethanhe42 requested changes

2024-10-17 06:21 UTC, ethanhe42 commented on nemo/collections/diffusion/models/dit/dit_layer_spec.py
> +class DiTLayer(TransformerLayer):
is this the same as the existing DiTLayerWithAdaLN?

2024-10-18 21:18 UTC, ethanhe42 approved these changes

2024-10-22 00:24 UTC, merged