ci: Improve VM maintenance
NVIDIA/NeMo pull request #10758
Opened 2024-10-04 08:41 UTC by ko3n1g

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-10-04 12:07 UTC, ko3n1g commented
Successful run: https://github.com/NVIDIA/NeMo/actions/runs/11178779025/job/31077046171

2024-10-10 15:19 UTC, pablo-garay requested changes

2024-10-10 15:19 UTC, pablo-garay commented on .github/workflows/node-reboot-single-vm.yml
> +            echo "Issues with GPU detected, will attempt a reboot & re-install."
I guess this message needs to be changed now since not rebooting

2024-10-10 15:19 UTC, pablo-garay commented on .github/workflows/node-reboot-single-vm.yml
> +  check-status-and-maybe-reboot:
I guess this job name needs to be changed since not rebooting

2024-10-25 14:21 UTC, merged