finetuning with Megatron  + HF lm
NVIDIA/NeMo pull request #1113
Opened 2020-09-03 23:32 UTC by ekmb

- [ ] [BioMegatron models added and will be automatically downloaded with NeMo

- [ ] tutorial on how to use Megatron-LM

- [ ] section on how to use HF lm models

https://colab.research.google.com/drive/1HLqyPelWTVyh5ZQugVqwMY5LmiENby-s?authuser=3#scrollTo=Wi_LBdSA4U6Q

2020-09-04 05:34 UTC, yzhang123 requested changes

2020-09-04 05:34 UTC, yzhang123 commented on README.rst
> +     - `03_Token_Classification_Named_Entity_Recognition.ipynb <https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/03_Token_Classification_Named_Entity_Recognition.ipynb>`_
can you postpone this renaming of existing file, i will get bad conflicts.

2020-09-04 05:34 UTC, yzhang123 commented on README.rst
> +     - `04_GLUE_Benchmark.ipynb <https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/04_GLUE_Benchmark.ipynb>`_
same here

2020-09-04 05:34 UTC, yzhang123 commented on README.rst
> +     - `05_Punctuation_and_Capitalization.ipynb <https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/05_Punctuation_and_Capitalization.ipynb>`_
same here

2020-09-04 05:34 UTC, yzhang123 commented on nemo/collections/nlp/modules/common/megatron/megatron_utils.py
> +        pretrained_mode_name: name of the pretrained model from the hugging face list,
this is megatron, so not huggingface list

2020-09-04 05:47 UTC, okuchaiev approved these changes
looks good to me

2020-09-04 07:00 UTC, yzhang123 reviewed
I have not checked notebooks so i cannot approve it formally, but Oleksii has approved, so he can merge it since he has admin rights. I'm ok with that given he has reviewed the notebooks
Rest looks good to me

2020-09-04 20:11 UTC, ekmb commented
> I have not checked notebooks so i cannot approve it formally, but Oleksii has approved, so he can merge it since he has admin rights. I'm ok with that given he has reviewed the notebooks
> Rest looks good to me

@okuchaiev up to you what to do with the PR

2020-09-09 22:14 UTC, yzhang123 approved these changes
same comment as above, fine given Oleksii reviewed the notebook

2020-09-11 18:44 UTC, merged