Added deprecation notice
NVIDIA/NeMo pull request #11133
Opened 2024-11-01 16:06 UTC by Ssofja

# What does this PR do ?
Some deprecation notices have added for future code refactoring 
Add a one line overview of what this PR aims to accomplish.

**Collection**: [asr]
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

2024-11-04 14:18 UTC, nithinraok commented on nemo/collections/asr/data/audio_to_text.py
> +@deprecated(explanation='It will be removed in future versions, please use LhotseSpeechToTextBpeDataset class ')
```suggestion
@deprecated(explanation='Webdataset support will be removed in r2.1.0 versions, please use LhotseSpeechToTextBpeDataset class instead')
```

2024-11-04 14:19 UTC, nithinraok commented on nemo/collections/asr/models/classification_models.py
> +@deprecated(explanation='It will be replaced with EncDecSpeakerLabelModel class.')
```suggestion
@deprecated(explanation='EncDecClassificationModel will be merged with EncDecSpeakerLabelModel class.')
```

2024-11-04 17:15 UTC, ko3n1g requested changes
small nit

2024-11-04 17:15 UTC, ko3n1g commented on nemo/collections/asr/data/audio_to_text.py
> +)
```suggestion
    explanation='Webdataset support will be removed in v2.1.0 versions, please use LhotseSpeechToTextBpeDataset class instead'
)
```

2024-11-04 18:23 UTC, titu1994 approved these changes
LGTM thanks !

2024-11-04 18:23 UTC, titu1994 commented on nemo/collections/asr/models/confidence_ensemble.py
> +@deprecated(version='2.1.0 NeMo')
```suggestion
@deprecated(version='v2.1.0')
```

2024-11-05 16:13 UTC, nithinraok approved these changes

2024-11-05 16:13 UTC, merged