adding canary docs
NVIDIA/NeMo pull request #11176
Opened 2024-11-06 02:11 UTC by krishnacpuvvada

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [ASR]

# Changelog 
- Adding docs for canary

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
 - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-11-06 16:53 UTC, nithinraok requested changes

2024-11-06 16:53 UTC, nithinraok commented on docs/source/asr/configs.rst
> +Multi-task AED Models
Is the following information present in the docs:
* What is Canary model 
* How to load a canary model and transcribe? 
* How to finetune a Canary model to adapt to new languages
* Same languages but new data -> tokenizer update
* Recommended hyper parameters for finetuning

2024-11-07 00:54 UTC, titu1994 reviewed
Overall looks like a good start but needs more details for setting up internals

2024-11-07 00:54 UTC, titu1994 commented on docs/source/asr/configs.rst
> +      bucket_duration_bins: [3.79, 4.82, 5.688, ..., 35.827]
Provide info / link to calcualte bucket duration bins (ir just update below sentence to mention that to get the list of floats, follow this link)

2024-11-07 00:54 UTC, titu1994 commented on docs/source/asr/configs.rst
> +The model uses special tokens for task control and language specification. These can be configured during tokenizer creation or loaded from an existing tokenizer:
we need docs how to construct this special tokenizer (either here or somewhere below and link to that section)

2024-11-07 00:54 UTC, titu1994 commented on docs/source/asr/configs.rst
> +~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~~
```

2024-11-07 00:54 UTC, titu1994 commented on docs/source/asr/images/aed_model.png
No picture upload. Upload to latest nemo release and update url

2024-12-06 18:45 UTC, titu1994 commented
@krishnacpuvvada  please address and merge

2024-12-30 02:00 UTC, closed without merging

2025-05-28 23:48 UTC, krishnacpuvvada commented on docs/source/asr/configs.rst
> +      bucket_duration_bins: [3.79, 4.82, 5.688, ..., 35.827]
done.

2025-05-29 00:02 UTC, krishnacpuvvada commented on docs/source/asr/configs.rst
> +~~~~~~~~~~~~~~~~~
done