Aligner/nemotron5
NVIDIA/NeMo pull request #11264
Opened 2024-11-12 20:13 UTC by arendu

# What does this PR do ?

place to make all changes to support nemotron5 training
**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2025-01-30 11:44 UTC, mikolajblaz requested changes
Left some comments, but it would be good for @dimapihtar to look as well since it changes NeMo 1 checkpointing logic

2025-01-30 11:44 UTC, mikolajblaz commented on nemo/collections/nlp/parts/nlp_overrides.py
> +                tmpdir = dist_ckpt_dir.parent
why is the whole previous code removed?
I'm pretty sure we can't do that

2025-01-30 11:44 UTC, mikolajblaz commented on nemo/utils/callbacks/nemo_model_checkpoint.py
> +                pl_module.save_to(
Why the new model is saved or not based on `remove_backup_path` flag?

2025-01-30 11:44 UTC, mikolajblaz commented on nemo/utils/callbacks/nemo_model_checkpoint.py
> +        output = super()._save_topk_checkpoint(*args, **kwargs)
wrap in 
```
try:
    output = super()._save_topk_checkpoint(*args, **kwargs)
finally:
    trainer.strategy.save_top_k = prev_save_top_k
```

2025-01-30 11:44 UTC, mikolajblaz commented on nemo/collections/nlp/parts/nlp_overrides.py
> +            if self.save_top_k:
I would suggest moving this logic out of the strategy, instead do the differentiation regular/.nemo save in the `save_checkpoint` method of the NeMoModelCallback. Otherwise there is so much entanglement in the logic.

2025-01-30 12:26 UTC, dimapihtar reviewed
can we run this PR once it's ready with nemo-ci nightly to make sure it doesn't break anything? Because I'm seeing a lot of checkpinting changes which can probably lead to ci failures.

2025-02-03 20:06 UTC, arendu commented on nemo/utils/callbacks/nemo_model_checkpoint.py
> +        output = super()._save_topk_checkpoint(*args, **kwargs)
cc @gshennvm

2025-02-03 20:07 UTC, arendu commented on nemo/utils/callbacks/nemo_model_checkpoint.py
> +                pl_module.save_to(
cc @gshennvm

2025-02-03 20:08 UTC, arendu commented on nemo/collections/nlp/parts/nlp_overrides.py
> +                tmpdir = dist_ckpt_dir.parent
We've been using this branch with no issues. I'll let @gshennvm  comment further.

2025-03-01 02:04 UTC, closed without merging