Add VLM scripts and CI tests
NVIDIA/NeMo pull request #11383
Opened 2024-11-22 19:12 UTC by yaoyu-33

# What does this PR do ?

Add VLM running scripts and github action CI tests.

**Collection**: [multimodal]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-11-22 19:41 UTC, cuichenx submitted a review, later dismissed
LGTM

2024-11-25 17:38 UTC, ko3n1g requested changes

2024-11-25 17:38 UTC, ko3n1g commented on .github/workflows/cicd-main.yml
> +        python tests/collections/vlm/mllama_train.py \
Please add the two tests also to the final check `CICD_Nemo_Test` (the large list with the `needs:` keyword)

2024-11-25 18:28 UTC, ko3n1g approved these changes

2024-11-27 17:56 UTC, ko3n1g submitted a review, later dismissed

2024-12-10 17:50 UTC, Victor49152 approved these changes

2024-12-10 19:01 UTC, pablo-garay approved these changes

2024-12-10 19:01 UTC, merged