Add non-mcore fsdp2 strategy
NVIDIA/NeMo pull request #11525
Opened 2024-12-09 23:36 UTC by BoxiangW

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2025-01-06 17:33 UTC, akoumpa commented on nemo/collections/llm/gpt/model/hf_auto_model_for_causal_lm.py
> +def parallelize(model, device_mesh: DeviceMesh):
@BoxiangW can you move this inside pytorch/strategies/fsdp2_strategy.py (maybe a utils.py)?

2025-01-06 17:43 UTC, akoumpa commented on tests/collections/llm/hf/sft_nemorun_fsdp2.py
> +    recipe.trainer.strategy = run.Config(nl.FSDP2Strategy, data_parallel_size=2, tensor_parallel_size=1)
can we also test TP?

2025-01-06 17:44 UTC, akoumpa commented on tests/collections/llm/hf/sft_nemorun_fsdp2.py
> +    run.run(recipe, executor=executor)
Can you add a check for peak memory usage after it run?

2025-01-06 19:25 UTC, BoxiangW commented on nemo/collections/llm/gpt/model/hf_auto_model_for_causal_lm.py
> +def parallelize(model, device_mesh: DeviceMesh):
We can move the FSDP part of this but the TP part need to setup a sharding plan which requires the layer names. It will look like this
```
# Parallelize the last linear out projection
        plan = {
            "model.embed_tokens": RowwiseParallel(input_layouts=Replicate()),
            # "model.norm": SequenceParallel(),
            "model.layers.0": PrepareModuleInput(
                input_layouts=(Replicate(),),
                desired_input_layouts=(Replicate(),),
                use_local_output=True,
            ),
            "lm_head": ColwiseParallel(
                input_layouts=Replicate(),
                output_layouts=Replicate(),
            ),
        }
        model = parallelize_module(model, tp_mesh, plan)

        # Parallelize each transformer block
        for transformer_block in model.model.layers:
            plan = {
                # "input_layernorm": SequenceParallel(),
                "self_attn": PrepareModuleInput(
                    input_layouts=Replicate(),
                    desired_input_layouts=Replicate(),
                ),
                "self_attn.q_proj": ColwiseParallel(),
                "self_attn.k_proj": ColwiseParallel(),
                "self_attn.v_proj": ColwiseParallel(),
                "self_attn.o_proj": RowwiseParallel(output_layouts=Replicate()),
                "mlp": PrepareModuleInput(
                    input_layouts=(Replicate(),),
                    desired_input_layouts=(Replicate(),),
                ),
                "mlp.gate_proj": ColwiseParallel(),
                "mlp.up_proj": ColwiseParallel(),
                "mlp.down_proj": RowwiseParallel(output_layouts=Replicate()),
                # "post_attention_layernorm": SequenceParallel(),
            }
```

2025-01-06 19:26 UTC, BoxiangW commented on tests/collections/llm/hf/sft_nemorun_fsdp2.py
> +    recipe.trainer.strategy = run.Config(nl.FSDP2Strategy, data_parallel_size=2, tensor_parallel_size=1)
TP is not yet supported in this PR. I added a check for now to make sure it is DP only.

2025-01-06 19:54 UTC, BoxiangW commented on nemo/collections/llm/gpt/model/hf_auto_model_for_causal_lm.py
> +def parallelize(model, device_mesh: DeviceMesh):
Done

2025-01-07 00:32 UTC, BoxiangW commented on tests/collections/llm/hf/sft_nemorun_fsdp2.py
> +    run.run(recipe, executor=executor)
I have added the memory test in another file tests/collections/llm/hf/sft_fsdp2.py

2025-01-08 18:04 UTC, akoumpa approved these changes

2025-01-08 18:24 UTC, ko3n1g requested changes
Please add the tests to the final step:)

2025-01-08 18:25 UTC, pablo-garay approved these changes

2025-01-08 18:29 UTC, pablo-garay approved these changes

2025-01-08 18:32 UTC, merged