NeMo 2.0 VLLM export
NVIDIA/NeMo pull request #11543
Opened 2024-12-11 15:39 UTC by Laplasjan107

# What does this PR do ?

VLLM export for NeMo 2.0 models

**Collection**: llm

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [X] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-12-23 13:25 UTC, janekl commented on nemo/export/sentencepiece_tokenizer.py
> +            self.tokenizer = tokenizer
could this go into some auxiliary method as it's also kind of repeated in L59-70?

2024-12-23 13:37 UTC, janekl commented on nemo/export/vllm/model_config.py
> +            for hf_arg, nemo_arg in hf_to_nemo_dict.items():
repeated in L144-153: maybe helper?

2024-12-23 17:57 UTC, oyilmaz-nvidia requested changes
Were you able to test this with a nemo 2 ckpt?

2024-12-23 17:57 UTC, oyilmaz-nvidia commented on nemo/export/vllm/engine.py
> +class VLLMTokenizerGroup(TokenizerGroup):
A minor thing but can we rename this to `vLLMTokenizerGroup`

2024-12-30 09:07 UTC, janekl commented
> Were you able to test this with a nemo 2 ckpt?

Yep, that's the very point here. Model types tested are Llama, Mixtral, Gemma, StarCoder2 to keep vLLM supported models parity with 24.07 release https://docs.nvidia.com/nemo-framework/user-guide/24.07/deployment/llm/optimized/index.html

2024-12-31 09:42 UTC, janekl commented on nemo/export/vllm/model_loader.py
> +from .utils import is_nemo2_checkpoint
Let's please keep one convention for imports so I think full-path like `from nemo.export.vllm.utils import ...`

2025-01-13 14:41 UTC, janekl approved these changes

2025-01-13 15:55 UTC, ko3n1g approved these changes

2025-01-13 16:39 UTC, oyilmaz-nvidia approved these changes
LGTM, thanks!

2025-01-13 17:50 UTC, merged