CTC decoders
NVIDIA/NeMo pull request #1319
Opened 2020-10-21 05:38 UTC by vsl9

- Added CTC beam search decoder (module, package installation)
- Added Offline ASR notebook for greedy decoding, words splitting, decoding with N-gram re-scoring

2020-10-21 05:40 UTC, vsl9 commented
Reviewers, please replace `main` branch with `ctc-decoders` in the notebook for testing in Colab.

2020-10-22 22:05 UTC, okuchaiev requested changes
thanks! looks good, just one minor comment

2020-10-22 22:05 UTC, okuchaiev commented on scripts/install_ctc_decoders.sh
> +git clone https://github.com/NVIDIA/OpenSeq2Seq -b ctc-decoders
can you please change this to checkout a specific commit or tag?

2020-10-22 22:54 UTC, okuchaiev approved these changes

2020-10-22 22:54 UTC, merged

2020-11-18 12:12 UTC, ShantanuNair commented
Quick question - does this PR mean that beam-searching using a Language Model (kenLM) is now supported at least partially? Just trying to keep track of the state of things :) We're all eagerly keeping track of the progress you guys are making.

2020-11-18 13:13 UTC, ShantanuNair commented
And apologies if this isn't the appropriate place for such questions (let me know) but it seems like the delay for the timestamps builds up more after each word, ending up with the timestamps not aligning with the right words at all. This could be because I'm running it on much longer (20-30minute) audio files instead of ~25s, but I figured that wouldn't be an issue since there's no RNN.