Dev deps cnt
NVIDIA/NeMo pull request #1732
Opened 2021-02-08 22:20 UTC by tkornuta-nvidia

- [x] Bumping version of EFF to 0.2.6 (changes required by Yang's PR to TLT)
- [x] Added 'nvidia-pyindex' to setup_requires

2021-02-10 12:04 UTC, borisfom approved these changes

2021-02-10 12:07 UTC, borisfom requested changes
Actually. this would break Mac and other platforms Nemo is being used on.

2021-02-10 21:37 UTC, borisfom commented on requirements/requirements.txt
> +onnx-graphsurgeon>=0.2.7
graph_surgeon should not go into requirements.txt but listed in ‘install_requires’ arg of setup.py - conditionally : if platform is one of those we currently have wheel published.

2021-02-11 22:37 UTC, borisfom commented
We should close this PR - its sole purpose was to enable ONNX export for Megatron (in Nemo b3 environment) - which we have found is broken anyway in b4 (due to Pytorch version).
So it does not solve the issue for our standard containers and introduces risks.

2021-02-12 03:31 UTC, tkornuta-nvidia commented
please note I still need EFF.

2021-02-16 05:21 UTC, merged