Fix the versioning on multi-node training.
NVIDIA/NeMo pull request #2016
Opened 2021-04-02 19:08 UTC by VahidooX

Used resume_if_exists instead of checking the Slurm to void creating the version folders. So whenever resume_if_exists  is enabled, we should skip creating the versions otherwise training can not continue.

2021-04-02 19:30 UTC, titu1994 reviewed
LGTM, @blisc for final review

2021-04-06 14:32 UTC, blisc requested changes

2021-04-06 14:32 UTC, blisc commented on nemo/utils/exp_manager.py
> +                )
Wouldn't it be more accurate to tell users to use `explicit_log_dir` when resuming, instead of using `exp_dir`/`name`/`version `?

2021-04-06 17:13 UTC, blisc requested changes
Please update the docstring of exp_manger so that it matches the new behaviour.
Please add a note that the behaviour of this argument changed as of version 1.0.0.

2021-04-06 18:42 UTC, VahidooX commented
> 
> 
> Please update the docstring of exp_manger so that it matches the new behaviour.
> Please add a note that the behaviour of this argument changed as of version 1.0.0.

Added to the docstring.

2021-04-06 18:49 UTC, blisc approved these changes

2021-04-06 18:52 UTC, titu1994 approved these changes
LGTM

2021-04-06 21:35 UTC, merged