Denormalization tutorial
NVIDIA/NeMo pull request #2034
Opened 2021-04-07 23:31 UTC by ekmb

2021-04-08 15:48 UTC, yzhang123 commented on tutorials/tools/Denormalizaion-Inverse_Text_Normalization.ipynb
> +    "transducer (WFST) grammars. The tool uses [`Pynini`](https://github.com/kylebgorman/pynini) to construct WFSTs, and the created grammars can be exported and integrated into [`Sparrowhawk`](https
NeMo ITN tool `can be seen` a Python extension of `Sparrowhawk

2021-04-08 15:49 UTC, yzhang123 commented on tutorials/tools/Denormalizaion-Inverse_Text_Normalization.ipynb
> +    "Currently, NeMo tool provides support for English language and the following semiotic classes from the [Google Text normalization dataset](https://www.kaggle.com/richardwilliamsproat/text-normal
for `English and` [..]

2021-04-08 16:01 UTC, yzhang123 reviewed
added comments, structure looks good

2021-04-08 16:01 UTC, yzhang123 commented on tutorials/tools/Denormalizaion-Inverse_Text_Normalization.ipynb
> +    "from nemo_tools.text_denormalization.denormalize import denormalize\n",
emphasize that ITN is part of package nemo_tools, which can be installed as shown in main README

2021-04-08 22:27 UTC, ekmb commented on tutorials/tools/Denormalizaion-Inverse_Text_Normalization.ipynb
> +    "Example evaluation run: python run_evaluate.py --input=./en_with_types/output-00001-of-00100 [--denormalizer nemo]"
done

2021-04-08 22:27 UTC, ekmb commented on tutorials/tools/Denormalizaion-Inverse_Text_Normalization.ipynb
> +    "A finite state transducer (FST) not only matches the pattern but also produces output according to the defined transition states."
done

2021-04-09 00:30 UTC, yzhang123 requested changes

2021-04-09 00:30 UTC, yzhang123 commented on tutorials/tools/Text_Denormalization_(Inverse_Text_Normalization).ipynb
> +    "- `classify()` - creates a linear automaton from the input string and composes it with the final classification WFST, which transduces numbers and inserts semantic tags.  \n",
they have different names now, could you use signature in current ode?
classify i think is find_tag + select_tag,
verbalize is find_veerbalize + select_verbalize
etc

2021-04-09 00:30 UTC, yzhang123 commented on docs/source/nemo_tools/text_denormalization.rst
> +ITN is the task of converting the raw spoken output of the ASR model into its written form to improve the text readability.
Could you do this in new sentence with --> arrows so the input -> output stands more out?

2021-04-09 16:22 UTC, yzhang123 approved these changes

2021-04-09 16:22 UTC, merged