Text Normalization Update
NVIDIA/NeMo pull request #2356
Opened 2021-06-14 17:49 UTC by ekmb

- added support for fractional numbers
- added support for roman numbers up to 1000 (audio-based normalization only)
- parallel normalization of manifests
- bug fixes and pre/post-processing updates to improve normalization coverage

2021-06-14 18:52 UTC, yzhang123 requested changes

2021-06-14 18:52 UTC, yzhang123 commented on nemo_text_processing/text_normalization/data/roman/ties.tsv
> +xc	90
don't forget to add __init__.py to all newly created directories

2021-06-14 18:52 UTC, yzhang123 commented on nemo_text_processing/text_normalization/data/whitelist.tsv
> +&Co.	and
what happends to Co? could you delete this entry?

2021-06-14 18:52 UTC, yzhang123 commented on nemo_text_processing/text_normalization/verbalizers/fraction.py
add doc string for class?

2021-06-14 18:52 UTC, yzhang123 commented on nemo_text_processing/text_normalization/verbalizers/roman.py
> +        e.g. tokens { electronic { username: "cdf1" domain: "abc.edu" } } -> c d f one at a b c dot e d u
adjust doc

2021-06-14 19:56 UTC, ekmb commented on nemo_text_processing/text_normalization/verbalizers/fraction.py
added doctring

2021-06-14 19:56 UTC, ekmb commented on nemo_text_processing/text_normalization/verbalizers/roman.py
> +        e.g. tokens { electronic { username: "cdf1" domain: "abc.edu" } } -> c d f one at a b c dot e d u
done

2021-06-15 01:17 UTC, yzhang123 approved these changes
could you please fix lgtm?

2021-06-15 01:26 UTC, merged

2021-06-15 01:26 UTC, ekmb commented
> could you please fix lgtm?

fixed already