Fixing a typo in Non_English_Downstream_Tasks (NER) tutorial
NVIDIA/NeMo pull request #2687
Opened 2021-08-17 23:13 UTC by pasandi20

2021-08-18 16:15 UTC, ericharper commented
Can you make the base branch `r1.3.0`?

2021-08-18 16:17 UTC, ericharper commented on tutorials/nlp/Non_English_Downstream_Tasks_(NER).ipynb
> +        "BRANCH = 'main'"
`main` should be `r1.3.0`

2021-08-18 16:18 UTC, ericharper requested changes
This is a bug fix for the r1.3.0 release. Please change the base branch of the PR and also change the pinned branch for the notebook.

2021-09-10 21:12 UTC, ekmb commented
@ericharper @pasandi20 is this PR still needed?

2021-11-13 01:10 UTC, okuchaiev commented
looks like this became obsolete. closing

2021-11-13 01:10 UTC, closed without merging