Update a few packages' version
NVIDIA/NeMo pull request #3134
Opened 2021-11-03 22:01 UTC by fayejf

2021-11-03 22:23 UTC, titu1994 requested changes
Overall looks great, but revert the PT >= 1.10 for now, we will update it in the future relese after subsequent 21.11 comes out.

2021-11-03 22:23 UTC, titu1994 commented on requirements/requirements.txt
> +torch>=1.10
This shouldnt be there, it will override container version of torch

2021-11-03 22:49 UTC, titu1994 submitted a review, later dismissed
LGTM, @ericharper for final approval before merge.

2021-11-04 16:24 UTC, ericharper approved these changes
LGTM. Thanks!

2021-11-04 16:24 UTC, merged