Self-supervised tutorial & update
NVIDIA/NeMo pull request #3344
Opened 2021-12-15 21:33 UTC by sam1373

- Basic tutorial for self-supervised pre-training and subsequent supervised fine-tuning
- Config for conformer SSL (may be changed later)
- Update to convert_to_tarred script to enable not having "text" field in manifest, and allow using "offset" for manifest without labels
- Add optional non-stride layers to reconstruction decoder
- Add option to load part of model from second nemo checkpoint from config (for example if we want to load encoder from one pre-trained model, and decoder from another)

2021-12-16 06:58 UTC, okuchaiev commented
/blossom-ci

2022-01-12 19:07 UTC, titu1994 reviewed
Initial comments. Will review note book in seperate comment.

2022-01-12 19:07 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +            with open_dict(cfg):
Update doc string for this

2022-01-12 19:07 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +            with open_dict(cfg):
Change name. This seems confusing.

2022-01-24 20:03 UTC, VahidooX requested changes

2022-01-24 21:17 UTC, sam1373 commented on examples/asr/conf/ssl/conformer/conformer_ssl.yaml
> +    freq_masks: 4
I have found it to work well

2022-01-24 21:18 UTC, sam1373 commented on nemo/core/classes/modelPT.py
> +                its state dict will be extracted. If loading from multiple files, you can pass in a dict
Added example

2022-01-24 21:20 UTC, sam1373 commented on examples/asr/conf/ssl/conformer/conformer_ssl.yaml
> +    proj_dim: *dec_out
No, they have to have the same values, and yes it is just a placeholder.

2022-01-26 05:09 UTC, VahidooX approved these changes
LGTM!

2022-01-26 17:44 UTC, merged