vad infer refactor
NVIDIA/NeMo pull request #3394
Opened 2022-01-06 08:25 UTC by fayejf

2022-01-06 20:07 UTC, fayejf commented on examples/asr/conf/vad_inference_postprocessing.yaml
> +    dont_auto_split: False # whether to automatically split manifest entry by split_duration to avoid potential CUDA out of memory issue.
Good point. Yeah, I used dont_auto_split because of store_true in argparser. Will update

2022-01-06 20:07 UTC, fayejf commented on examples/asr/conf/vad_inference_postprocessing.yaml
> +out_manifest_filepath: null # if not specifym it will autautomatically be "vad_out.json"
Sounds great. Will update

2022-01-06 20:09 UTC, fayejf commented on nemo/collections/asr/parts/utils/vad_utils.py
> +        time_len (float): length of window for generating the frame.
Let me unify all of them to be window_length_in_sec and shift_length_in_sec to reduce confusion.

2022-01-07 23:10 UTC, fayejf commented
This PR should be merged after https://github.com/NVIDIA/NeMo/pull/3392 and https://github.com/NVIDIA/NeMo/pull/3359

2022-01-08 02:48 UTC, fayejf commented
Reflected @tango4j 's suggestion. Since this PR is getting bigger. Will cover the doc (some update about renaming) update alongside doc update in another PR

2022-01-10 23:05 UTC, tango4j approved these changes

2022-01-10 23:12 UTC, tango4j requested changes

2022-01-10 23:12 UTC, tango4j commented on examples/asr/conf/vad_inference_postprocessing.yaml
> +# {"audio_filepath": "/path/to/audio_file", "offset": 0, "duration": null, "label": "infer", "text": "-"}
We'd better make sure this refactoring makes no bugs or issues before merging it.

2022-01-11 21:33 UTC, nithinraok approved these changes
LGTM

2022-01-12 07:14 UTC, tango4j approved these changes

2022-01-12 19:27 UTC, nithinraok approved these changes

2022-01-13 01:32 UTC, merged