Updated Speech Data Explorer
NVIDIA/NeMo pull request #3710
Opened 2022-02-18 18:10 UTC by vsl9

# What does this PR do ?

Adds support of recent versions of Dash and librosa. Adds new features (metrics, export, UI).

**Collection**: Tools

# Changelog 
- Ported SDE to Plotly Dash 2.1, librosa 0.9
- Added new metrics (insertions, deletions, diff)
- Added support for downloading sorted/filtered vocabulary
- Updated UI

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [X] New Feature
- [X] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to #3395

2022-02-24 18:14 UTC, ekmb requested changes

2022-02-24 18:14 UTC, ekmb commented on tools/speech_data_explorer/data_explorer.py
> +        fo.write(','.join(vocabulary_view[0].keys()) + '\n')
This results in an extra unnamed column, shared the screenshot offline

2022-02-24 18:14 UTC, ekmb commented on tools/speech_data_explorer/data_explorer.py
> +                data[-1]['D-I'] = measures['deletions'] - measures['insertions']
Maybe rename D to `D (Deletion)` in the table form, same for I? Since the abbreviation wasn't introduced in the Statistics tab, unlike CER, WER?

2022-02-27 19:33 UTC, ahkarami commented
@vsl9 
Thanks for this pull request. These modifications are really helpful. I would be very grateful to you if you address the problem (OOV & lexicon issue) raised in the link below:
https://github.com/NVIDIA/NeMo/issues/3568
Best

2022-03-03 06:22 UTC, ekmb approved these changes

2022-03-03 07:14 UTC, merged