adding ranking baseline determ
NVIDIA/NeMo pull request #3739
Opened 2022-02-23 17:47 UTC by yzhang123

Signed-off-by: Yang Zhang <yangzhang@nvidia.com>

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-02-23 18:16 UTC, ekmb requested changes

2022-02-23 18:16 UTC, ekmb commented on nemo_text_processing/text_normalization/en/taggers/whitelist.py
> -        # if lm:
we need this for thresholding

2022-02-23 18:16 UTC, ekmb commented on nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify_baseline.py
> +                | pynutil.add_weight(date_graph, 1.1)
date 1.09 to match default TN

2022-02-23 18:16 UTC, ekmb commented on nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify_baseline.py
> +            time_final = pynini.compose(time_graph, v_time_graph)
is this one used?

2022-02-23 22:18 UTC, yzhang123 commented on nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify_baseline.py
> +            time_final = pynini.compose(time_graph, v_time_graph)
no deleted

2022-02-23 22:18 UTC, yzhang123 commented on nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify_baseline.py
> +                | pynutil.add_weight(date_graph, 1.1)
done, also updated whitelist to 1.01

2022-02-23 22:18 UTC, yzhang123 commented on nemo_text_processing/text_normalization/en/taggers/whitelist.py
> -        # if lm:
ok moved back comment

2022-02-24 00:22 UTC, ekmb approved these changes

2022-02-24 00:22 UTC, merged