Merge r1.7.1 to main
NVIDIA/NeMo pull request #3824
Opened 2022-03-10 01:28 UTC by ericharper

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-03-10 17:57 UTC, vadam5 requested changes
Looks good other than my one comment in `megatron_gpt_model.py`

2022-03-10 17:57 UTC, vadam5 commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> -        if self.use_soft_prompts:
I don't think this if/else statement should be removed

2022-03-10 17:58 UTC, vadam5 commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> +>
Also this should be deleted

2022-03-10 22:59 UTC, MaximumEntropy submitted a review, later dismissed
LGTM!

2022-03-11 21:00 UTC, vadam5 approved these changes
LGTM!

2022-03-14 01:46 UTC, merged