Sven
NVIDIA/NeMo pull request #3842
Opened 2022-03-14 22:44 UTC by svenchilton

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-03-15 00:02 UTC, titu1994 reviewed
Approved for ASR changes. @blisc for TTS, @ekmb  for NLP

2022-03-15 14:14 UTC, blisc requested changes

2022-03-15 14:14 UTC, blisc commented on tutorials/tts/FastPitch_MixerTTS_Training.ipynb
> +    "You can deploy the models you trained with NeMo on [NVIDIA Riva](https://developer.nvidia.com/riva)!"
Let's change the word in all TTS notebooks into 
```
You can deploy certain NeMo models you trained on [NVIDIA Riva](https://developer.nvidia.com/riva)! For a list of supported TTS models, please refer to the [Nvidia Riva TTS documentation](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/service-tts.html).
```

2022-05-25 19:01 UTC, titu1994 commented
Closing due to inactivity. Please recreate new pr if required.

2022-05-25 19:01 UTC, closed without merging