Tacotron2 retrain
NVIDIA/NeMo pull request #4103
Opened 2022-05-03 16:11 UTC by treacker

Refactoring Tacotron2 to use new TTSDataset class

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-05-03 19:01 UTC, blisc requested changes

2022-05-03 19:01 UTC, blisc commented on examples/tts/conf/tacotron2.yaml
> -name: Tacotron2
Let's keep this name as is.

2022-05-03 19:01 UTC, blisc commented on nemo/collections/tts/models/tacotron2.py
>          )
Let's do something like: https://github.com/NVIDIA/NeMo/pull/4008/files#diff-eaf0251e9d829a2b3aa53d9d90c6ca8181cc52d02be139215cc8baffc986e7acR99
Where we check if it's using the old dataset class and if it is, print a warning message and setup the parser the old way. Else, set up the parser the new way.

2022-05-03 21:31 UTC, treacker commented on requirements/requirements.txt
> +numpy==1.21
I was getting error for conflicting versions with numba if numpy version or greater than 1.21

2022-05-04 15:17 UTC, blisc commented on nemo/collections/tts/models/tacotron2.py
> +        self.text_embedding = nn.Embedding(self.num_tokens, 512)
I still don't understand how bos and eos are handled. Your embedding only has self.num_tokens but you pass in self.num_tokens+1 here: https://github.com/NVIDIA/NeMo/pull/4103/files#diff-ebdd6ab591a0b633b1bea4d397fa6a561a5ee187193d8a0bcb30a605f9ae94c7R135

2022-05-04 15:17 UTC, blisc commented on nemo/collections/tts/models/tacotron2.py
> +        self.audio_to_melspec_precessor = instantiate(cfg.preprocessor, highfreq=cfg.train_ds.dataset.highfreq)
Let's add the parameter in the yaml config instead of doing `highfreq=cfg.train_ds.dataset.highfreq`

2022-05-04 15:17 UTC, blisc commented on nemo/collections/tts/models/tacotron2.py
>          )
You need to use the tokenzier here. `self.vocab` as far as I'm aware doesn't exist in this model, and the check should be against `nemo.collections.asr.data.audio_to_text.AudioToCharDataset` which is the old dataset in the yaml that you editted. Vs `nemo.collections.tts.torch.data.TTSDataset` which is the new one

2022-05-06 08:14 UTC, treacker reviewed
Both old and new checkpoints/yaml configs work fine.

2022-05-06 15:18 UTC, blisc commented on examples/tts/conf/tacotron2.yaml
> +      batch_size: 1
Why a batch of 1 for validation?

2022-05-06 18:34 UTC, blisc approved these changes
Let's fix the CI and we should be good to merge

2022-05-06 20:46 UTC, treacker commented
I cannot see what is the problem with jenkins check, it says site cant be reached

2022-05-11 15:25 UTC, merged