Fix speaker utils
NVIDIA/NeMo pull request #4138
Opened 2022-05-09 19:58 UTC by tango4j

# What does this PR do ?

This PR fixes bugs for certain cases and adds few functions.

**Collection**: [Note which collection this PR will affect]

ASR

# Changelog 
- Add specific line by line info of high level changes in this PR.

Added following functions in speaker_utils.py.
These functions are needed to extract oracle VAD stamp from manfiest file, considering the offset and duration.

get_uniq_id_with_dur()
getSubRangeList()
getMinMaxOfRangeList()
getMergedRanges()
int2fl()
fl2int()
combine_int_overlaps()
combine_float_overlaps()
getOverlapRange()
isOverlap()

Details can be found in the docstring in each function definition.

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [x] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-05-10 17:22 UTC, titu1994 commented
/blossom-ci

2022-05-10 17:25 UTC, titu1994 commented
/blossom-ci

2022-05-10 17:30 UTC, nithinraok requested changes

2022-05-10 17:30 UTC, nithinraok commented on nemo/collections/asr/parts/utils/speaker_utils.py
> +    bare_uniq_id = meta['audio_filepath'].split('/')[-1].split('.wav')[0]
same here as mentioned above for uniqname fix

2022-05-10 17:30 UTC, nithinraok commented on nemo/collections/asr/parts/utils/speaker_utils.py
> +    Write the json dictionary into the specified file.
specified file -> specified manifest file

2022-05-19 02:54 UTC, tango4j commented on nemo/collections/asr/parts/utils/speaker_utils.py
>          basename = os.path.basename(filepath).rsplit('.', 1)[0]
Replaced with the line Yang has changed.

2022-05-19 02:57 UTC, tango4j commented on nemo/collections/asr/parts/utils/speaker_utils.py
> +    Write the json dictionary into the specified file.
added "manifest'.

2022-05-25 20:57 UTC, merged