Support larger datasets for question answering
NVIDIA/NeMo pull request #4205
Opened 2022-05-19 02:59 UTC by Zhilin123

# What does this PR do ?

Support larger datasets for question answering 

**Collection**: NLP

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-06-04 01:56 UTC, yzhang123 requested changes

2022-06-04 23:57 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
Sure!

2022-06-04 23:59 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    print(f'Found {len(intents)} intents')
sure

2022-06-05 00:03 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    """ Put training files in convenient place for conversion to our format. """
Sure

2022-06-05 00:10 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    our_infold = infold + "/dataset"
This copying of files into a unified dir should have been designed for downstream functions to locate all relevant files efficiently.  This is mainly used on the assistant dataset (10s of MB) so space/time from rearranging the files might have been ok as convenience was the original intention (the initial external directory was rather messy).

2022-06-05 00:10 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    Find a lost of unique slot types in training and testing data.
sure

2022-06-05 00:11 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    We use a single slot type name both for starting and continuation tokes (not using B-, I- notation).
sure

2022-06-05 00:12 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    print(f'Found {len(slots)} slot types')
sure updated

2022-06-05 00:14 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/assistant_utils.py
> +    """ Convert each word in a query to corresponding slot number. """
sure

2022-06-05 00:21 UTC, Zhilin123 commented on examples/nlp/intent_slot_classification/data/import_datasets.py
> +def process_atis(infold, outfold, modes=['train', 'test'], do_lower_case=False):
sure

2022-06-05 00:29 UTC, Zhilin123 commented on tutorials/nlp/Dialogue.ipynb
> +        "!git clone https://github.com/NVIDIA/NeMo --branch r1.9.0\n",
I think maybe r1.9.0 might be best for now as future stable releases might have code/dependency changes that accidentally render this tutorial not able to be used.

2022-06-05 00:31 UTC, Zhilin123 commented on nemo/collections/nlp/models/question_answering/qa_model.py
> +        with autocast():
sure

2022-06-05 03:50 UTC, yzhang123 approved these changes

2022-06-05 04:43 UTC, merged