Merge r1.9.0 main
NVIDIA/NeMo pull request #4331
Opened 2022-06-03 21:37 UTC by ericharper

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-06-04 01:18 UTC, vadam5 approved these changes
All the prompt learning doc/notebook/config changes look good to me!

2022-06-06 21:54 UTC, yzhang123 requested changes

2022-06-06 21:54 UTC, yzhang123 commented on tests/nemo_text_processing/en/data_text_normalization/test_cases_whitelist.txt
> +dr. Evil~dr . Evil
this needs to be deleted

2022-06-06 21:54 UTC, yzhang123 commented on tests/nemo_text_processing/en/data_text_normalization/test_cases_time.txt
> +11:30...~eleven thirty . . .
to delete

2022-06-06 21:54 UTC, yzhang123 commented on tests/nemo_text_processing/en/data_text_normalization/test_cases_word.txt
> +1!hello~one ! hello
to delete

2022-06-06 21:54 UTC, yzhang123 commented on tests/nemo_text_processing/en/data_text_normalization/test_cases_word.txt
> +love him while we may,~love him while we may ,
no space before comma at end:
correct test case:
love him while we may,~love him while we may,

2022-06-07 00:44 UTC, titu1994 submitted a review, later dismissed
Looks good !

2022-06-07 19:19 UTC, yzhang123 approved these changes

2022-06-07 21:03 UTC, merged