T5 rpe fix 01
NVIDIA/NeMo pull request #4440
Opened 2022-06-24 14:31 UTC by khcs

# What does this PR do ?

Fix the RPE implementation converging slower with loss consistently higher than NeMo APE and Megatron-LM RPE implementation.

**Collection**: NLP

# Changelog 
- Changed how RPE parameters are initialized and passed on.

# Usage
* Train with `model.position_embedding_type='relative'` config.

```python
python /home/workspace/NeMo/examples/nlp/language_modeling/megatron_t5_pretraining.py model.position_embedding_type='relative'
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [x] Bugfix
- [ ] Documentation

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-06-24 21:30 UTC, MaximumEntropy requested changes
Thanks for the fixes! :) A few comments

2022-06-24 23:04 UTC, khcs commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +            bidirectional=(self.layer_type == LayerType.decoder),  # (self.is_decoder),
Thanks, you're right! Changed to `bidirectional=(self.attention_type != AttnMaskType.causal)`.

2022-06-24 23:06 UTC, khcs commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +        has_relative_attention_bias=False,
Yes, this is a little confusing - we compute the `position_bias` only for the first layer of Encoder/Decoder, and initialize it with zeros for the Decoder first cross-attention layer.

2022-06-24 23:07 UTC, khcs commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +                    position_bias = torch.zeros(1, key_length, key_length)
Good point, though with the way currently is initializes them on GPU, but wouldn't hurt to add `.to(device)` to make sure ;)

2022-06-24 23:09 UTC, khcs commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +                    position_bias = torch.zeros(1, key_length, key_length)
Oh, perhaps to make sure they're on the right device for when using tensor-/pipeline- parallel?

2022-06-26 21:26 UTC, MaximumEntropy requested changes
Changes for position_embedding_type's default.

2022-06-26 21:26 UTC, MaximumEntropy commented on nemo/collections/nlp/models/language_modeling/megatron_lm_encoder_decoder_model.py
> +            if self.cfg.position_embedding_type != 'relative':
To make this backward compatibile to old models without `position_embedding_type`, you will need to use `self.cfg.get('position_embedding_type', 'learned_absolute')`.

2022-06-26 21:26 UTC, MaximumEntropy commented on nemo/collections/nlp/models/language_modeling/megatron_lm_encoder_decoder_model.py
> +            if self.cfg.position_embedding_type != 'relative':
This is why CI is failing on the BART test right now.

2022-06-27 16:26 UTC, okuchaiev commented
/blossom-ci

2022-06-29 21:50 UTC, closed without merging