Changes to make Megatron NMT exportable
NVIDIA/NeMo pull request #4499
Opened 2022-07-05 19:13 UTC by Davood-M

# What does this PR do ?

Adding requirements to make Megatron NMT exportable

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Added input/output types for encoder/decoder/tokens_head
- Added input_example

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [X] New Feature
- [ ] Bugfix
- [ ] Documentation

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

2022-07-08 21:48 UTC, borisfom commented on nemo/collections/nlp/modules/common/megatron/fused_bias_gelu.py
> +    @staticmethod
Does that work for ONNX->TRT translation or only for ORT ?

2022-07-12 00:08 UTC, MaximumEntropy reviewed
Minor comment on dtype setting.

2022-07-12 00:15 UTC, MaximumEntropy commented
@ericharper what do you think about having separate `xx_module.py` files for the different modules versus moving all of them into a single file?

2022-07-12 00:25 UTC, MaximumEntropy requested changes
Just marking as needs changes temporarily to get @ericharper's review.

2022-07-13 21:45 UTC, Davood-M commented on nemo/utils/export_utils.py
> +            mod = nn.LayerNorm(n.weight.shape, eps=n.epsilon, elementwise_affine=True, dtype=torch.float16,).to(dev)
Yes. Without setting the dtype, it raises the following error:

```python
Traceback (most recent call last):
  File "***", line 245, in <module>
    encoder_instance.export('***/encoder.onnx')
  File "***/NeMo/nemo/core/classes/exportable.py", line 68, in export
    out, descr, out_example = model._export(
  File "***/NeMo/nemo/core/classes/exportable.py", line 142, in _export
    output_example = tuple(self.forward(*input_list, **input_dict))
  File "nemo2onnx-experimental.py", line 166, in forward
    return self.encoder(
  File "***/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "***/NeMo/nemo/collections/nlp/modules/common/megatron/megatron_transformer_encoder.py", line 156, in forward
    enc_output = self.model(
  File "***/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "***/NeMo/nemo/collections/nlp/modules/common/megatron/transformer.py", line 1819, in forward
    output = self.final_layernorm(output)
  File "***/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "***/NeMo/nemo/utils/export_utils.py", line 56, in forward
    ret = self.mod.forward(x)
  File "***/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "***/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
```

2022-07-18 16:49 UTC, ericharper commented on nemo/collections/nlp/models/machine_translation/megatron_nmt_model.py
> +    def __init__(self, decoder_embedding, decoder, device='cuda:0'):
See device comment above.

2022-07-18 16:49 UTC, ericharper commented on nemo/collections/nlp/models/machine_translation/megatron_nmt_model.py
> +    def __init__(self, encoder_embedding, encoder, device='cuda:0'):
See device comment above.

2022-07-18 16:51 UTC, ericharper commented on nemo/collections/nlp/models/machine_translation/megatron_nmt_model.py
> +class DecWEmb(torch.nn.Module, Exportable):
See module comment above.

2022-07-18 16:51 UTC, ericharper commented on nemo/collections/nlp/models/machine_translation/megatron_nmt_model.py
> +class EncWEmb(torch.nn.Module, Exportable):
See module comment above.

2022-07-18 16:53 UTC, ericharper commented on nemo/collections/nlp/models/machine_translation/megatron_nmt_model.py
> +        return TokensHeadWEmb(self.enc_dec_model.decoder_embedding, self.enc_dec_model.tokens_head)
Shouldn't these be going into a base class? Also, can you consider changing the suffix `WEmb` Maybe just remove the `W`?

2022-07-18 17:27 UTC, ericharper commented on nemo/collections/nlp/modules/common/megatron/megatron_decoder_module.py
> +        return ['decoder_output']
Why do you need names property? Don't you already have the name in the input_type?

2022-07-18 17:27 UTC, ericharper commented on nemo/collections/nlp/modules/common/megatron/megatron_encoder_module.py
> +        return ['encoder_output']
See names comment above.

2022-07-18 17:28 UTC, ericharper commented on nemo/collections/nlp/modules/common/megatron/megatron_tokens_head_module.py
> +        return ['logits']
See name comment above.

2022-07-18 17:31 UTC, ericharper requested changes
Finished my first review. Overall a great PR! But I think it still need some refactoring.

Please see my comments.

2022-08-09 18:28 UTC, merged

2022-08-09 18:54 UTC, Davood-M commented
reopening PR