Fix runtime check
NVIDIA/NeMo pull request #4501
Opened 2022-07-06 01:53 UTC by borisfom

# What does this PR do ?
Post-export runtime check refinements - allow checking multiple input sizes.
Restored max_dim argument functionality in export.py
Also, added a cast to ensure ASR nets are always exported with output in FP32 - even with autocast.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-07-06 03:13 UTC, titu1994 requested changes
Overall looks good, minor fix needed regarding recursive call and dtype

2022-07-06 03:13 UTC, titu1994 commented on nemo/collections/asr/models/asr_model.py
> +        return cast_all(ret, from_dtype=torch.float16, to_dtype=torch.float)
Isn't torch.float = torch.float64 by default ?

2022-07-06 03:13 UTC, titu1994 commented on nemo/utils/export_utils.py
> +def cast_all(x, from_dtype=torch.float16, to_dtype=torch.float):
Same comment as above. Should be explicit to fp32?

2022-07-06 03:13 UTC, titu1994 commented on nemo/utils/export_utils.py
> +            return new_dict
This should pass the user provided values, not the explicit defaults.

2022-07-08 01:07 UTC, borisfom commented on nemo/collections/asr/models/asr_model.py
> +        return cast_all(ret, from_dtype=torch.float16, to_dtype=torch.float)
Nope. But sure let's use float32 here.

2022-07-08 22:30 UTC, titu1994 approved these changes
Looks fantaastic

2022-07-08 22:31 UTC, merged