add profiling interface
NVIDIA/NeMo pull request #4531
Opened 2022-07-08 22:27 UTC by erhoo82

# What does this PR do ?

The interface to generate nsys profile results. 

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Enable profile
- Specify range to profile by batch step
- Specify rank to profile
- Specify profiling details

# Usage
Enable knobs to profile

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-07-08 22:43 UTC, MaximumEntropy reviewed
Minor comments about logging.

2022-07-08 22:43 UTC, MaximumEntropy commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> +            print("====== Start nsys profiling ======")
Can we change these to `logging.info()` messages?

2022-07-08 22:43 UTC, MaximumEntropy commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> +            print("====== End nsys profiling ======")
Same here, can we make these `logging.info()` calls?

2022-07-11 21:18 UTC, titu1994 requested changes

2022-07-11 21:18 UTC, titu1994 commented on examples/nlp/language_modeling/conf/megatron_gpt_config.yaml
> +  nsys_profile: False
Can you make it a nested config. IE

```yaml
nsys_profiler:
  profile: False
  profile_start_step: 10  # Global batch to start profiling
  profile_end_step: 10 # Global batch to end profiling
  profile_ranks: [0] # Global rank IDs to profile
  profile_gen_shape: False # Generate model and kernel details including input shapes

```

2022-07-11 21:18 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +            nsys_profile: False
Update syntax for nested config

2022-07-11 21:18 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +            self._nsys_profile_start_step = self.cfg.nsys_profile_start_step
These values should be obtained via self.cfg.get(xyz, <reasonable default>)

2022-07-11 22:33 UTC, closed without merging