Support listing Hugging Face model info
NVIDIA/NeMo pull request #4619
Opened 2022-07-26 23:02 UTC by titu1994

Signed-off-by: smajumdar <smajumdar@nvidia.com>

# What does this PR do ?

Add new apis to filter and obtain NeMo hugging face models via code.

**Collection**: [Core]

# Changelog 
- Adds two methods `get_hf_model_filter()` and `list_available_models_on_hf(model_filter=None)` to ModelPT.
- First method returns a basic ModelFilter object, can be overridden by the user. Used as default to next method if nothing is provided.
- `list_available_models_on_hf()` lists the nemo models that satisfy the filter.

# Usage

```python
from nemo.core import ModelPT

filt = ModelPT.get_hf_model_filter()
filt.task = ['automatic-speech-recognition']
    
model_info = ModelPT.list_available_models_on_hf(filt)
print("Num available :", len(model_info))

for info in model_info:
    print(info)
    print()

# Select one model and restore - 
model = ModelPT.from_pretrained(model_info[0].modelId)  # some NeMo model

``

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ x New Feature
- [ ] Bugfix
- [ ] Documentation

2022-07-26 23:36 UTC, okuchaiev commented on nemo/core/classes/common.py
> +    def get_hf_model_filter(cls) -> ModelFilter:
why this method needs to be public?

2022-07-26 23:40 UTC, okuchaiev requested changes
Let's extend ``list_available_models`` method instead to accept optional ModelFilter instance. By default should be None and should list both NGC and HF models (even if duplicated). Then make ``list_available_models_on_hf`` private and call it under the hood

2022-07-27 19:05 UTC, ericharper commented
> Let's extend `list_available_models` method instead to accept optional ModelFilter instance. By default should be None and should list both NGC and HF models (even if duplicated). Then make `list_available_models_on_hf` private and call it under the hood

I agree with this. We don't want users to have to use two different methods to list models.

2022-07-27 19:10 UTC, titu1994 commented
Reasons states above : it would require updating every single class that implements list_available_models which is impractical

2022-07-27 20:13 UTC, okuchaiev submitted a review, later dismissed

2022-07-27 20:21 UTC, titu1994 commented
Updated PR with different name for method to remove confusion against list_available_models

2022-07-27 21:08 UTC, ericharper approved these changes
LGTM. Thanks for the changes!

2022-07-27 22:12 UTC, merged