Reverted cahced_property to Python 3.7 friendly version.
NVIDIA/NeMo pull request #4749
Opened 2022-08-17 13:15 UTC by michalivne

Signed-off-by: Micha Livne <mlivne@cs.toronto.edu>

# What does this PR do ?

Revert to colab Python 3.7friendly version of cached_property

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-08-17 15:56 UTC, Zhilin123 requested changes
Can you try the suggestion below? Also I can't seem to fetch this branch 'michalivne:megatron-python-3.7-compatibility' on colab for testing on my side. If you can verify that this code below doesn't break your functionality, I can create an identical PR that has a branch on the NVIDIA account (instead of michalivne) so that I can test it on the colab side.

2022-08-17 15:56 UTC, Zhilin123 commented on nemo/collections/nlp/models/language_modeling/megatron_lm_encoder_decoder_model.py
> +    # property
Can you try `
@functools.property
@functools.lru_cache(maxsize=None)
`?

2022-08-17 15:56 UTC, Zhilin123 commented on nemo/collections/nlp/models/language_modeling/megatron_lm_encoder_decoder_model.py
> +    # property
Each of them should be in a line of its own

2022-08-22 23:34 UTC, closed without merging

2022-08-22 23:35 UTC, michalivne commented
A new PR has been created by @Zhilin123