Retro eval
NVIDIA/NeMo pull request #4985
Opened 2022-09-22 20:37 UTC by yidong72

# What does this PR do ?

Refactor the text generation code to be model independent by using different inference strategies.

Added the GPT inference strategy and prompt learning inference strategy and verify they are working properly.

Implement the RETRO model text generation and fix a default bias problem.

2022-09-26 21:06 UTC, okuchaiev commented
@vadam5  can you please review this with respect to GPT
@MaximumEntropy can you please review this with respect to T5?

2022-09-26 21:09 UTC, MaximumEntropy reviewed
Minor comments.

2022-09-26 21:13 UTC, yidong72 commented on examples/nlp/language_modeling/conf/megatron_retro_inference.yaml
> +prompts: # prompts for GPT inference
you are right. fixed

2022-09-26 21:15 UTC, yidong72 commented on examples/nlp/language_modeling/megatron_retro_eval.py
> +        model_cfg.masked_softmax_fusion = False
good catch. fixed

2022-09-26 21:20 UTC, yidong72 commented on nemo/collections/nlp/models/language_modeling/megatron_retrieval_model.py
> +        averaged_loss = torch.stack(outputs).mean()
because in the validation step, the returned loss is already averaged across the data parallel_group. This is redudant.

2022-09-26 21:20 UTC, yidong72 commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +        default_biase = self.cross_attention.dense.bias
fixed

2022-09-26 21:20 UTC, yidong72 commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +                return torch.zeros_like(hidden_states), default_biase
fixed

2022-09-26 21:20 UTC, yidong72 commented on nemo/collections/nlp/modules/common/megatron/transformer.py
> +            return torch.zeros_like(hidden_states), default_biase
fixed

2022-09-30 16:54 UTC, vadam5 requested changes
Thanks for the refactor of prompt learning/gpt model inference code! Overall looks good, just left a few comments.

2022-09-30 16:54 UTC, vadam5 commented on nemo/collections/nlp/modules/common/text_generation_utils.py
> +    # tokens, attention_mask, position_ids = get_batch(model, tokenizer, context_tokens_tensor)
This comment can be deleted

2022-09-30 19:02 UTC, yidong72 commented on examples/nlp/language_modeling/megatron_retro_eval.py
> +        python megatron_gpt_eval.py \
Good catch. fixed.

2022-09-30 19:04 UTC, yidong72 commented on examples/nlp/language_modeling/conf/megatron_retro_inference.yaml
> +server: False  # whether launch the inference server
agree. I will remove it

2022-09-30 19:06 UTC, yidong72 commented on nemo/collections/nlp/modules/common/text_generation_utils.py
> +    # tokens, attention_mask, position_ids = get_batch(model, tokenizer, context_tokens_tensor)
removed

2022-09-30 21:14 UTC, vadam5 approved these changes
LGTM! Thank you

2022-10-02 03:38 UTC, merged