Punctuation capitalization model docs
NVIDIA/NeMo pull request #5030
Opened 2022-09-28 16:56 UTC by jubick1337

# What does this PR do ?

Adds docs for p&c lexical audio model

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [X] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-09-28 19:12 UTC, ekmb requested changes
This doc should be added to the NLP tasks list. How about refactoring similar to this doc: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/neural_models.html? P&C task page that has a link to the default and default + acoustic models?

2022-09-28 19:12 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +    model = PunctuationCapitalizationLexicalAudioModel.from_pretrained("PLACEHOLDER")
use `restore_from .. <PATH to .nemo file>` until chpts are released

2022-09-28 19:27 UTC, jubick1337 commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +    We recommend you try this model in a Jupyter notebook (run on `Google's Colab <https://colab.research.google.com/notebooks/intro.ipynb>`_.): `NeMo/tutorials/nlp/Punctuation_and_Capitalization_Lex
@ekmb not really but it's more of a common problem, nothing to do with tutorial itself IMO

2022-09-30 01:32 UTC, ekmb requested changes

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +Long audios are split into corresponding sequences of :code:`4000 * max_seq_length`.
what does this mean? what are audio/text files restrictions for this model?

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_models.rst
> +NeMo provides two types of Punctuation And Capitalization Models:
this should be moved after line 15

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization.rst
> +Audio data should be stored in ``audio_train.txt`` and ``audio_dev.txt`` (and optionally ``test.txt```). Each line in the ``audio_train.txt/audio_dev.txt/audio_test.txt`` should represent one calid p
why are these audio-related format details in the text-only model?

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +    We recommend you try this model in a Jupyter notebook (run on `Google's Colab <https://colab.research.google.com/notebooks/intro.ipynb>`_.): `NeMo/tutorials/nlp/Punctuation_and_Capitalization_Lex
please re-run, the default tutorial works in colab

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +    # Download and load the pre-trained BERT-based model
irrelevant comment

2022-09-30 01:32 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +In the addition to Punctuation and Capitalization model we add audio encoder (e.g. Conformer's encoder) and attention based fusion of lexical and audio features.
add link to the text only model here

2022-09-30 17:12 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +  This page contains only paraemters specific to lexical and audio model. Others parameters can be found in `Punctuation And Capitalization's page <https://docs.nvidia.com/deeplearning/nemo/user-guid
typo in `paraemters`

2022-09-30 17:12 UTC, ekmb commented on docs/source/nlp/punctuation_and_capitalization_lexical_audio.rst
> +Long audios are split just like in text only case, audio sequences treated the same as text seqences except :code:`max_seq_length` for audio equals :code:`max_seq_length*4000`.
how are these text/audio chucks are aligned?

2022-10-04 16:38 UTC, closed without merging