add yaml file for stateless transducer ASR model
NVIDIA/NeMo pull request #5608
Opened 2022-12-13 00:29 UTC by hainan-xv

# What does this PR do ?

This PR adds a yaml file for the conformer transducer model with a stateless decoder.

**Collection**: 

ASR

# Changelog 

# Usage

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2022-12-13 01:15 UTC, fayejf requested changes

2022-12-13 01:15 UTC, fayejf commented on examples/asr/conf/conformer/conformer_stateless_transducer_bpe.yaml
> +# Here are the recommended configs for different variants of Conformer-Transducer, other parameters are the same as in this config file.
Do we need to update the table below?

2022-12-13 01:15 UTC, fayejf commented on examples/asr/conf/conformer/conformer_stateless_transducer_bpe.yaml
> +# It contains the default values for training a Conformer-Transducer ASR model with stateless decoder, large size (~120M) with Transducer loss and sub-word encoding.
Could you add this to NeMo doc?  such as [here]( https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/models.html#conformer-transducer )

2022-12-14 18:37 UTC, titu1994 reviewed
LGTM, lets fix Fei's comments

2022-12-14 18:37 UTC, titu1994 commented on examples/asr/conf/conformer/conformer_stateless_transducer_bpe.yaml
> +# It contains the default values for training a Conformer-Transducer ASR model with stateless decoder, large size (~120M) with Transducer loss and sub-word encoding.
This file should be part of a subfolder - not directly inside of conformed. So conformer/stateless/...yaml

2022-12-14 18:37 UTC, titu1994 commented on examples/asr/conf/conformer/conformer_stateless_transducer_bpe.yaml
> +# Here are the recommended configs for different variants of Conformer-Transducer, other parameters are the same as in this config file.
+1

2023-04-09 01:52 UTC, closed without merging