Add AutoConfigurator (former HP Tool)
NVIDIA/NeMo pull request #5661
Opened 2022-12-16 22:07 UTC by markelsanz14

# What does this PR do ?
Adds AutoConfigurator to NeMo Megatron directory.

**Collection**: nemo_megatron_launcher

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [X] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?
@okuchaiev @yaoyu-33 @ericharper @Davood-M 

# Additional Information
* Related to # (issue)

2022-12-19 20:17 UTC, ericharper commented
Can you fix the style with `python setup.py style --fix` ?

2022-12-19 20:19 UTC, ericharper commented
Please also look into the Code scanning results.

2022-12-20 18:23 UTC, ericharper commented on nemo_megatron_launcher/auto_configurator/autoconfig/training_config.py
> +"""Prepares and launches the training HP search using bignlp-scripts."""
can change bignlp -> nemo megatron launcher

2022-12-20 18:32 UTC, ericharper requested changes
Please see the code scanning alerts and a few files are still missing copyrights.

2022-12-20 18:43 UTC, titu1994 requested changes
This must go to a NeMo tool repo.

Refer to https://github.com/NVIDIA/NeMo/pull/5657#pullrequestreview-1224968295

2022-12-20 22:37 UTC, dimapihtar requested changes
Plaese check @ericharper comments about code scanning.

2023-01-11 00:17 UTC, markelsanz14 commented
I think this PR is ready. Please confirm if ready @ericharper @okuchaiev

2023-01-11 18:02 UTC, closed without merging