[ASR] Separate Audio-to-Text (BPE, Char) dataset construction
NVIDIA/NeMo pull request #5774
Opened 2023-01-11 17:02 UTC by artbataev

Signed-off-by: Vladimir Bataev <vbataev@nvidia.com>

# What does this PR do ?

Separate Audio-to-Text Char and BPE dataset construction:
- this allows to use datasets for further mixing (e.g. in hybrid ASR-TTS models #5659)
- removes duplicated code from CTC, RNNT (Char and BPE) models

**Collection**: [ASR]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
from nemo.collections.asr.data.audio_to_text_dataset import get_audio_to_text_bpe_dataset_from_config

dataset = get_audio_to_text_bpe_dataset_from_config(...)  # construct BPE dataset from parameters
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-01-17 15:13 UTC, vsl9 commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +            logging.warning(f"Concat dataset requires `contact_sampling` but it was not provided. Config: {config}")
`contact_sampling` => `concat_sampling`

2023-01-17 15:14 UTC, vsl9 commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +                f"Concat dataset requires `contact_probabilities` list but it was not provided. Config: {config}"
`contact_probabilities` => `concat_probabilities`

2023-01-17 15:15 UTC, vsl9 commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +                logging.warning(f"`contact_probabilities` need to sum to 1. Config: {config}")
`contact_probabilities` => `concat_probabilities`

2023-01-19 15:23 UTC, artbataev commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +                logging.warning(f"`contact_probabilities` need to sum to 1. Config: {config}")
Fixed

2023-01-19 15:23 UTC, artbataev commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +                f"Concat dataset requires `contact_probabilities` list but it was not provided. Config: {config}"
Fixed

2023-01-19 15:23 UTC, artbataev commented on nemo/collections/asr/data/audio_to_text_dataset.py
> +            logging.warning(f"Concat dataset requires `contact_sampling` but it was not provided. Config: {config}")
Fixed

2023-01-24 07:42 UTC, vsl9 approved these changes
Thanks for the refactoring!

2023-01-24 18:34 UTC, titu1994 requested changes
As we discussed on slack, I don't believe this PR should be merged. It is simply higher level function of already high level functions that support this. It reduces flexibility for classes that will not be able to support all features at once such as Dali, tarred, bucketing etc. 

Please keep the code separated, and duplicated as needed. We may have classes on the future which will be built that do not support all code at once
We can revisit this in the future if we see there are no classes that require special handling

2023-01-31 18:42 UTC, titu1994 approved these changes
Lgtm for now, we'll revisit the design in the future

2023-01-31 18:42 UTC, merged