Add segmentation export to Audacity label file
NVIDIA/NeMo pull request #5857
Opened 2023-01-25 09:33 UTC by Ca-ressemble-a-du-fake

# What does this PR do ?

This PR adds the export of the segmentation file to a label file that can directly be imported in Audacity to quickly and easily assess the quality of the segmentation.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* No usage change. The label file will be automatically generated.

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-01-25 17:23 UTC, ekmb requested changes
@Ca-ressemble-a-du-fake thank you for your contribution!

2023-01-25 17:23 UTC, ekmb commented on tools/ctc_segmentation/scripts/utils.py
> +                    score = -0.2
`start, end, score = x` -> `start, end, _ = x` and 
`score = -0.2` should be removed since `score` is not written in the file

2023-02-02 04:51 UTC, Ca-ressemble-a-du-fake commented on tools/ctc_segmentation/scripts/utils.py
> +                    score = -0.2
At last I managed to do it (first PR update)! You should see the requested changes now

2023-02-02 05:21 UTC, ekmb commented on tools/ctc_segmentation/scripts/utils.py
> +                    score = -0.2
> At last I managed to do it (first PR update)! You should see the requested changes now

Thank you for your contribution!

2023-02-02 05:21 UTC, ekmb approved these changes

2023-02-02 16:31 UTC, merged