[TTS][refactor] Part 4 - nn.collections.tts.g2p.modules
NVIDIA/NeMo pull request #6111
Opened 2023-02-24 21:16 UTC by XuesongYang

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-02-25 22:05 UTC, XuesongYang commented on tests/collections/asr/test_hybrid_asr_tts_models.py
> +@pytest.mark.pleasefixme
@artbataev for vis.

2023-02-25 22:05 UTC, XuesongYang commented on tests/collections/asr/test_hybrid_asr_tts_models.py
> +@pytest.mark.pleasefixme
@artbataev for vis.

2023-02-25 22:06 UTC, XuesongYang commented on tests/collections/tts/test_tts_exportables.py
> +@pytest.mark.pleasefixme
@borisfom for vis.

2023-02-25 22:06 UTC, XuesongYang commented on tests/collections/tts/test_tts_exportables.py
> +    @pytest.mark.pleasefixme
@borisfom for vis.

2023-02-26 07:01 UTC, artbataev requested changes
Please, do not make breaking changes.
This will significantly impact the teamwork and make our users and contributors unhappy.
This also violates NeMo's policy regarding breaking changes.

I think some good solutions exist for this problem:
1. If I understand correctly, you moved the classes from `nemo.collections.tts.g2p` to `nemo.collections.common.g2p`. So, it is possible to preserve compatibility by allowing them to be imported from the old modules
e.g. in `nemo.collections.tts.g2p.modules.IPAG2P' use 
```python
from nemo.collections.common.g2p.i18n_ipa import IpaG2p as IPAG2P

__all__ = [“IPAG2P”]
```
and so on.

Or use a **better solution with inheritance + deprecation warning**
```python
from nemo.collections.common.g2p.i18n_ipa import IpaG2p as NewIpaG2p
from nemo.utils.decorators.deprecated import deprecated

@deprecated(...)
class IPAG2P(NewIpaG2p):
    ...
```

2. If it is impossible to apply the first solution, provide a guide + scripts to convert existing checkpoints to make them compatible with the new version.

2023-02-26 07:47 UTC, titu1994 commented
Agreed, do not make backward compatibility breaking changes without following NeMo guidelines and appropriate release timeline for such changes (1-2 months of deprecated label, followed by removal). 

It doesn't seem you need to break anything jf you forward imports correctly, ASR does something similar - see https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/features.py#L39

Plus avoid adding dependencies to commons that are optional dependencies - difficult to install things like apex and numba should avoid commons as much as possible so as not to impose restrictions on other domains.

2023-02-27 22:11 UTC, XuesongYang commented
converted this PR to a draft for improvements.

2023-03-07 17:20 UTC, XuesongYang commented
I added safeguard for TTS model inference: https://github.com/NVIDIA/NeMo/pull/6129.

2023-03-14 21:16 UTC, redoctopus reviewed
Are we sure we want to move G2P into `common`? I thought part of the reason it was moved back to the `tts` collection was because no other parts of NeMo actually use the G2P classes. Would it be clearer to rename the files in-place or move them to somewhere else in the TTS collection?

@ekmb @rlangman any thoughts?

2023-03-16 06:38 UTC, XuesongYang commented
> Are we sure we want to move G2P into `common`? I thought part of the reason it was moved back to the `tts` collection was because no other parts of NeMo actually use the G2P classes. Would it be clearer to rename the files in-place or move them to somewhere else in the TTS collection?

G2P is a common tool for phoneme-based ASR, although recent research mostly focuses on sub-word units. So that's why I am thinking to promote g2p under `nemo.collections.common.g2p`. 

An alternative place to host g2p is under `nemo.collections.g2p` in parallel with `asr`, `nlp`, and `tts`. Then we can maintain similar sub-directory as tts/asr, and move g2p models under `nemo.collections.g2p.models`

2023-03-16 18:23 UTC, redoctopus commented
> G2P is a common tool for phoneme-based ASR, although recent research mostly focuses on sub-word units. So that's why I am thinking to promote g2p under nemo.collections.common.g2p.

We don't have this yet, right? So this would be a forward-looking change? That's fine with me, as long as we're relatively certain we'll follow-through and not just have to move it back into TTS.

@titu1994 and @ekmb to solicit opinions about where to put these.

2023-03-16 18:39 UTC, ekmb commented
> > G2P is a common tool for phoneme-based ASR, although recent research mostly focuses on sub-word units. So that's why I am thinking to promote g2p under nemo.collections.common.g2p.
> 
> We don't have this yet, right? So this would be a forward-looking change? That's fine with me, as long as we're relatively certain we'll follow-through and not just have to move it back into TTS.
> 
> @titu1994 and @ekmb to solicit opinions about where to put these.

I would keep g2p in the TTS along with neural G2P models unless other collections use it. Rule-based G2P development (if any) will be happening in the NeMo-text-processing repo.
Could you add a subfolder for g2p models to separate them from TTS models (https://github.com/NVIDIA/NeMo/tree/refactor-tts-g2p-module/nemo/collections/tts)/models/?

2023-03-20 20:44 UTC, XuesongYang commented
> > > > G2P is a common tool for phoneme-based ASR, although recent research mostly focuses on sub-word units. So that's why I am thinking to promote g2p under nemo.collections.common.g2p.
> > > 
> > > 
> > > We don't have this yet, right? So this would be a forward-looking change? That's fine with me, as long as we're relatively certain we'll follow-through and not just have to move it back into TTS.
> > > @titu1994 and @ekmb to solicit opinions about where to put these.
> > 
> > 
> > I would keep g2p in the TTS along with neural G2P models unless other collections use it. Rule-based G2P development (if any) will be happening in the NeMo-text-processing repo. Could you add a subfolder for g2p models to separate them from TTS models (https://github.com/NVIDIA/NeMo/tree/refactor-tts-g2p-module/nemo/collections/tts)/models/?
> 
> The G2P in NeMo (non-neural modules) actually are rule-based ones. They should be merged into nemo-text-processing repo in the future I guess. Since most of you guys suggested moving g2p under tts folder, then two possible structures are shown below, which one do you guys prefer? @ekmb @redoctopus @rlangman. **Option 1**
> 
> ```
> nemo/collections/tts/models
> - base.py # move BaseG2p class into this file.
> - ...
> - g2p_en_us_arpabet.py
> - g2p_i18n_ipa.py
> - g2p_zh_cn_pinyin.py
> - g2p_ctc.py
> - g2p_heteronym_classification.py
> - g2p_t5.py
> - ...
> ```
> 
> **Option 2**
> 
> ```
> nemo/collections/tts/models/g2p
> - base.py # only contains BaseG2p class in this file.
> - en_us_arpabet.py
> - i18n_ipa.py
> - zh_cn_pinyin.py
> - ctc.py
> - heteronym_classification.py
> - t5.py
> ```

Discussed with folks offline, we finally decided to proceed with the below option,
```
- nemo/collections/tts/g2p/data
  - ctc.py
  - heteronym_classification.py
  - t5.py
- nemo/collections/tts/g2p/models
  - base.py # only contains BaseG2p class in this file.
  - en_us_arpabet.py
  - i18n_ipa.py
  - zh_cn_pinyin.py
  - ctc.py
  - heteronym_classification.py
  - t5.py
- nemo/collections/tts/g2p/utils.py
```

2023-03-21 20:48 UTC, redoctopus approved these changes
LGTM!

2023-03-21 20:56 UTC, merged