[ASR] Support audio_filepath as a list of single-channel files
NVIDIA/NeMo pull request #6132
Opened 2023-03-04 02:49 UTC by anteju

# What does this PR do ?

Currently, multichannel audio can be used in `audio_filepath` by providing a path to a multichannel file.
This PR adds support for `audio_path` to specify multichannel audio by providing a list of paths to single-channel files.

**Collection**: ASR

# Changelog 

- `AudioSegment.from_file` can load multichannel audio from a list of paths to single-channel audio files
- `manifest.get_full_path` supports lists as input and can resolve path to each path in a list
- Added unit tests for `AudioSegment`
	- `TestAudioSegment:: test_audio_segment_from_file` for existing functionality, loading a single file
	- `TestAudioSegment:: test_audio_segment_multichannel_with_list ` for new functionality, loading multiple single-channel files
- Added unit tests for `manifest.get_full_path`
	- `TestPreprocessingUtils:: test_get_full_path_local` when resolving local paths, both single paths and lists
	- `TestPreprocessingUtils:: test_get_full_path_ais` when resolving paths pointing to AIStore, both single paths and lists

# Usage

## Example scripts
- [examples.zip](https://github.com/NVIDIA/NeMo/files/10887310/examples.zip)

## Description

Currently, ASR models can be used to transcribe multichannel audio by providing a path to a multichannel audio file in `audio_filepath` and selecting a single channel using `channel_selector`.
This PR adds an option to set `audio_filepath` to a list of paths to individual channels, each containing a single channel. This is useful in situations where multichannel audio is provided as individual channels.

Two examples with `audio_filepath` containing a list of paths to single-channel files are provided below.
The first example is directly using `transcribe()` od an `ASRModel`. The second example is running `speech_to_text_eval.py`.

### Example 1

This example will check if `asr_model.transcribe` is working the same when a path to multichannel audio is provided as

- a path to a multichannel audio file (this is currently supported)
- a list of paths to single-channel audio files (added in this PR)

In both cases, channel_selector can be used to pick one channel from the input multichannel audio.

The test will run with two different models: `stt_en_conformer_ctc_small` and `stt_en_conformer_transducer_small` and each of the 3 available channels.

To run the test:

```
python test_asr_model_transcribe.py
```

### Example 2

This example will check if `speech_to_text_eval.py` is working the same when a path to multichannel audio is provided as

- a path to a multichannel audio file (this is currently supported)
- a list of paths to single-channel audio files (added in this PR)

In both cases, channel_selector can be used to pick one channel from the input multichannel audio.

The test will run with two different models: `stt_en_conformer_ctc_small` and `stt_en_conformer_transducer_small` and each of the 3 available channels.

To run the test:

```
python test_speech_to_text_eval.py --nemo-dir PATH_TO_NEMO_DIR
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-03-09 01:58 UTC, titu1994 requested changes
Code looks ok, but there are sections that are very sensitive to changes and break a lot of underlying data loaders so I'm reluctant to merge this with changes to critical sections

2023-03-09 01:58 UTC, titu1994 commented on examples/asr/transcribe_speech.py
> +        Union[int, str]
Hmm dunno about this, hydra doesn't support optional union and we don't test this script in CI (or maybe we do with an old QN model). Did you test this locally ?

2023-03-09 01:58 UTC, titu1994 commented on nemo/collections/asr/parts/preprocessing/segment.py
> +            # files and concatenate them along the channel dimension
What if user names mistakes and send list of two different file here ? Can we detect and raise error?

2023-03-09 01:58 UTC, titu1994 commented on nemo/collections/asr/parts/utils/transcribe_utils.py
> -                if not audio_file.is_file() and not audio_file.is_absolute():
In reluctant to change any of this. It has severe negative interaction with tarred datasets and filename size limits.

2023-03-09 01:58 UTC, titu1994 commented on tests/collections/asr/utils/test_audio_utils.py
> +        "num_channels, channel_selectors", [(1, [None, 'average', 0]), (3, [None, 'average', 0, 1, [0, 1]]),]
Can you add a few tests - 
- File path longer than 255 chars 
- filename longer than 255 chars
- two audio files incorrectly passed as different channel (raise appropriate error)

2023-03-09 03:08 UTC, titu1994 commented on tests/collections/asr/utils/test_audio_utils.py
> +        "num_channels, channel_selectors", [(1, [None, 'average', 0]), (3, [None, 'average', 0, 1, [0, 1]]),]
Ok that seems like a reasonable error for (3). Let's add (1-2) then merge if they pass

2023-03-09 20:01 UTC, tango4j requested changes

2023-03-17 22:58 UTC, tango4j commented on nemo/collections/asr/parts/preprocessing/segment.py
> +            for a_file in audio_file:
Thanks after code-QL is addressed, we can merge I guess

2023-03-17 23:48 UTC, tango4j approved these changes
AudioSegment.from_file() works as expected with real-life multichannel files and 
all my requested changes are reflected.
+ Need to check other reviewers before getting merged

2023-03-18 00:30 UTC, fayejf requested changes
need some clarification before I approve. Thanks

2023-03-18 00:30 UTC, fayejf commented on nemo/collections/asr/parts/utils/transcribe_utils.py
> +                audio_file = get_full_path(audio_file=item[audio_key], manifest_file=cfg.dataset_manifest)
so we need both audio_dir and manifest to locate the path of the audio file just like in your example file? 

`{"audio_filepath": ["61-70968-3-4-5_ch_0.wav", "61-70968-3-4-5_ch_1.wav", "61-70968-3-4-5_ch_2.wav"], "text": "he was like unto my father in a way and yet was not my father", "offset": 0, "duration": 4.32}`

2023-03-20 18:42 UTC, fayejf commented on nemo/collections/asr/parts/utils/transcribe_utils.py
> +                audio_file = get_full_path(audio_file=item[audio_key], manifest_file=cfg.dataset_manifest)
oh I see! Thanks for clarification!

2023-03-20 18:43 UTC, fayejf approved these changes
LGTM! Thanks!

2023-03-20 19:08 UTC, titu1994 approved these changes
Changes look great, thanks !

2023-03-20 19:08 UTC, titu1994 commented on examples/asr/transcribe_speech.py
> +        Union[int, str]
Indeed union works now with the specifics that only primitive types are in the union

2023-03-20 19:08 UTC, titu1994 commented on tests/collections/asr/utils/test_audio_utils.py
> +        "num_channels, channel_selectors", [(1, [None, 'average', 0]), (3, [None, 'average', 0, 1, [0, 1]]),]
Perfect thanks !

2023-03-20 19:12 UTC, merged