fixed scanning alert bugs
NVIDIA/NeMo pull request #6177
Opened 2023-03-11 08:14 UTC by MikyasDesta

# What does this PR do ?

Fixes these issues
#5933 https://github.com/NVIDIA/NeMo/issues/5933 
#5937  https://github.com/NVIDIA/NeMo/issues/5937

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-03-11 08:17 UTC, MikyasDesta commented
@XuesongYang Can you approve this please?

2023-03-12 04:14 UTC, XuesongYang commented on nemo/collections/tts/modules/common.py
> +            raise Exception("{} affine model not supported".format(affine_model))
We mostly use f-string, i.e. `f"Affine model is not supported: {affine_model}. Please choose either 'wavenet' or 'simple_conv' instead."`.

Besides, This is a `ValueError`. Could you please replace `Exception` with `ValueError`? Thanks.

2023-03-12 04:14 UTC, XuesongYang requested changes
Thank you for your fix! Appreciate that.

2023-03-12 04:14 UTC, XuesongYang commented on nemo/collections/tts/modules/common.py
> +            raise Exception("{} scaling fn not supported".format(scaling_fn))
same comment as above.

2023-03-13 19:33 UTC, XuesongYang commented on nemo/collections/tts/modules/common.py
> +            raise Exception("{} scaling fn not supported".format(scaling_fn))
`scaling_fn` --> `self.scaling_fn`

2023-03-13 23:31 UTC, XuesongYang commented
close this PR. Please review https://github.com/NVIDIA/NeMo/pull/6177

2023-03-13 23:31 UTC, closed without merging