[WIP] add buffered chunked streaming for nemo force aligner
NVIDIA/NeMo pull request #6185
Opened 2023-03-13 20:42 UTC by Slyne

# What does this PR do ?
To support buffered chunked streaming inference for nemo neural force aligner.

**Collection**: [Note which collection this PR will affect]
ASR

# Changelog 
- add an argument (keep_logits default is False) for transcribe function in `FrameBatchASR` to keep the inference logits.
- return the logits(log probs) if keep_logits is set to True.

# Usage

```python
python align.py \
        pretrained_name="stt_en_citrinet_1024_gamma_0_25" \
        batch_size=32 \
        model_downsample_factor=8 \
        manifest_filepath=$manifest \
        use_buffered_chunked_streaming=true \
        output_dir=./buffered_streaming_test_pred \
        total_buffer_in_secs=10 \
        align_using_pred_text=true
```

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-03-29 21:17 UTC, erastorgueva-nv commented on tools/nemo_forced_aligner/align.py
> +            asr_model=model, frame_len=chunk_len, total_buffer=cfg.total_buffer_in_secs, batch_size=cfg.batch_size,
Please make a separate parameter, maybe called `chunk_batch_size`, and default value maybe 32 to pass in as the `FrameBatchASR` `batch_size` parameter. This parameter corresponds to the number of buffers in a batch (with the buffers coming from the same audio file).

2023-03-29 21:18 UTC, erastorgueva-nv requested changes
Thank you for this PR Slyne. Please modify the FrameBatchASR parameter as described in the comment.

2023-03-29 21:22 UTC, erastorgueva-nv commented
cc @jbalam-nv for visibility on changes to streaming_utils. I don't think they will break anything.
We need to add self.decoder, self.cfg and self.preprocessor attributes to FrameBatchASR so we can use them downstream in NFA. We also add some keep_logits flags but they are False by default.

2023-03-30 21:17 UTC, jbalam-nv submitted a review, later dismissed
LGTM

2023-03-30 21:19 UTC, erastorgueva-nv approved these changes

2023-04-04 02:40 UTC, erastorgueva-nv approved these changes
LGTM, this is the same as before

2023-04-04 06:01 UTC, titu1994 reviewed
Overall it looks awesome ! Minor comments, feel free to ignore for now

2023-04-04 06:01 UTC, titu1994 commented on nemo/collections/asr/parts/utils/streaming_utils.py
> +        for log_prob in self.all_logits:
Could you put this in a function? I feel like it gets repeated a lot

2023-04-04 21:14 UTC, merged