Add fix to resume pre-training when val outputs is empty
NVIDIA/NeMo pull request #6281
Opened 2023-03-23 18:19 UTC by athitten

# What does this PR do ?

Resuming pre-training sometimes fails immediately complaining of empty validation outputs tensor. This PR provides a fix for this issue.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-03-23 18:40 UTC, arendu commented on nemo/collections/nlp/models/language_modeling/megatron_lm_encoder_decoder_model.py
> +        if len(outputs) == 0:
same as other comment.

2023-03-23 18:40 UTC, arendu commented on nemo/collections/nlp/models/language_modeling/megatron_bert_model.py
> +        if len(outputs) == 0:
same as other comment.

2023-03-23 20:06 UTC, arendu approved these changes
LGTM!

2023-03-23 21:48 UTC, okuchaiev requested changes
Shouldn't this go to r1.17.0 instead of main?

2023-03-23 22:13 UTC, athitten commented
> Shouldn't this go to r1.17.0 instead of main?

@okuchaiev yes I missed to base it off of r1.17 instead of main. Let me do that.

2023-04-18 15:05 UTC, yzhang123 commented
> > Shouldn't this go to r1.17.0 instead of main?
> 
> @okuchaiev yes I missed to base it off of r1.17 instead of main. Let me do that.
could this be merged please?

2023-05-01 17:05 UTC, okuchaiev commented
lets merge this 1.18.0 ? @ericharper what do you think?

2023-05-24 01:55 UTC, closed without merging