Modular SpeechLLM implementation for Sept. 2023 submission (SALM)
NVIDIA/NeMo pull request #7634
Opened 2023-10-04 15:49 UTC by zhehuaichen

# What does this PR do ?

Include Modular SpeechLLM implementation for Sept. 2023 submission (SALM). The implementation integrates a pretrained FC and a frozen LLM, and can do ASR, AST, and in-context learning for keyword boosting.

The current implementation is based off of r1.20.0 release.

**Collection**: multimodal

# Usage

refer to `workspace/run_sft_audio_lm.py`

# Before your PR is "Ready for review"
**Pre checks**:
- [x] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [x] Did you write any new necessary tests?
- [x] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

2023-10-08 23:03 UTC, stevehuang52 commented
> @zhehuaichen why merging to https://github.com/NVIDIA/NeMo/tree/modular_speechllm ? instead of main? What is the purpose of files in workspace/* folder?

@nithinraok Because the project is still under development, and we want to put the branch under NVIDIA/NeMo to facilitate collaboration with more people

2023-10-08 23:06 UTC, stevehuang52 commented on tests/collections/multimodal/test_speechllm_models.py
> +# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
2023

2023-10-08 23:11 UTC, stevehuang52 requested changes
Overall LTGM, but let's remove the `workspace/scripts` and `workspace/tools` folders since the main branch has LLaMA support already.

2023-10-09 14:49 UTC, zhehuaichen commented on tests/collections/multimodal/test_speechllm_models.py
> +# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
done

2023-10-09 15:03 UTC, stevehuang52 approved these changes
LGTM, thanks~

2023-10-09 15:07 UTC, merged