Shinwool/upstream from bionemo utils scheduler
NVIDIA/NeMo pull request #7662
Opened 2023-10-09 03:13 UTC by citygyraffe

# What does this PR do ?

Adds a LR scheduler policy (LinearWarmupHoldDecayPolicy) that has following properties:
- Phase 1: linear warmup from 0 to the optimizer's learning rate
- Phase 2: constant phase
- Phase 3: linear decay to 'min_lr'
- Phase 4: constant phase at 'min_lr'
A visual representation of above is included in code.

**Collection**: N/A

# Changelog 
- Added class for LR scheduler policy (LinearWarmupHoldDecayPolicy)
- Added unit test for above

# Usage

# Before your PR is "Ready for review"
**Pre checks**:
- [v] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [v] Did you write any new necessary tests?
- [v] Did you add or update any necessary documentation?
- [x] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [v] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-10-09 23:30 UTC, ericharper commented on nemo/core/optim/lr_scheduler.py
> +        assert warmup_ratio is None or max_steps is not None, "If there is a " "ratio, there should be a total steps"
Could you use f-strings to display the values of the offending variables in the error message?

2023-10-24 02:44 UTC, citygyraffe commented
keep-alive

2023-10-31 22:22 UTC, ericharper commented
jenkins

2023-10-31 22:23 UTC, ericharper requested changes
Just one small comment. Please use f-strings.

2023-11-01 00:09 UTC, titu1994 commented on nemo/core/optim/lr_scheduler.py
Name of such class is by conversion "Annealing' at the end, not Policy. Though it's fine since it's just convention

2023-11-22 01:46 UTC, closed without merging