Add LoRA support to all linear layers
NVIDIA/NeMo pull request #7988
Opened 2023-12-07 00:31 UTC by ertkonuk

# What does this PR do ?

Add LoRA support to all linear transformations in Attention and MLP modules in NeMo and MCore GPT models.

**Collection**: [Note which collection this PR will affect]
nlp

# Usage
To add LoRa to specific layer, just add the **target_modules** parameter to lora_tuning. The available configuration are below:

```yaml    
lora_tuning:
      target_modules: ['attention_qkv'] # default, adds LoRA to QKV projection layer
      target_modules: ['attention_qkv','attention_dense'] # adds LoRA to QKV projection and Dense layers attention
      target_modules: ['mlp_fc1','mlp_fc2']# adds LoRA to linear layers in the MLP module
      target_modules: ['attention_qkv','attention_dense','mlp_fc1','mlp_fc2'] # adds LoRA to every linear layer in attention and MLP modules
```
There are also shortcut options defined as below:
```yaml    
lora_tuning:
      target_modules: ['attention'] # same as ['attention_qkv','attention_dense']
      target_modules: ['mlp'] # same as  ['mlp_fc1','mlp_fc2']
      target_modules: ['attention','mlp'] # same as ['attention_qkv','attention_dense','mlp_fc1','mlp_fc2']
      target_modules: ['all'] # same as ['attention_qkv','attention_dense','mlp_fc1','mlp_fc2']
```
If the target_modules parameter is not provided by the user, the default value is  
```yaml 
 target_modules: ['attention_qkv']
```
**PR Type**:
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?
@arendu

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2023-12-11 20:11 UTC, arendu submitted a review, later dismissed
Looks Good! @ertkonuk have you run some tests offline?

2023-12-19 03:55 UTC, cuichenx reviewed
All changes look good to me as well! As long as all code paths are tested offline.

2023-12-21 01:09 UTC, arendu commented
jenkins

2024-01-11 01:46 UTC, closed without merging

2024-01-16 19:37 UTC, arendu commented
jenkins

2024-01-25 10:31 UTC, michal2409 submitted a review, later dismissed

2024-01-31 19:53 UTC, cuichenx requested changes
unfortunately the forward function of `MCoreSelfAttentionMixin` has become out of date with the current mcore attention forward function... could you update this please?

2024-02-05 17:08 UTC, ertkonuk commented on nemo/collections/nlp/modules/common/megatron/adapters/mcore_mixins.py
> +
Thanks for the feedback. I updated MCoreSelfAttentionMixin and MCoreMLPMixin.

2024-02-05 21:34 UTC, arendu commented
jenkins

2024-02-05 21:57 UTC, cuichenx submitted a review, later dismissed
LGTM, thanks!

2024-02-05 23:06 UTC, arendu commented
jenkins

2024-02-06 03:23 UTC, arendu commented
jenkins

2024-02-06 16:45 UTC, arendu commented
jenkins

2024-02-07 02:10 UTC, HeyyyyyyG commented
jenkins

2024-02-07 21:06 UTC, cuichenx commented
jenkins

2024-02-08 05:14 UTC, HeyyyyyyG commented
jenkins

2024-02-09 01:31 UTC, cuichenx commented
jenkins

2024-02-09 17:34 UTC, HeyyyyyyG commented
jenkins

2024-02-12 22:16 UTC, cuichenx commented
jenkins

2024-02-12 22:27 UTC, cuichenx commented
jenkins

2024-02-13 17:28 UTC, cuichenx approved these changes

2024-02-13 17:36 UTC, cuichenx commented
jenkins

2024-02-14 19:36 UTC, arendu commented
jenkins

2024-02-14 22:55 UTC, cuichenx commented
jenkins

2024-02-15 21:21 UTC, cuichenx commented
jenkins

2024-02-20 15:41 UTC, cuichenx commented
jenkins

2024-02-20 18:49 UTC, cuichenx commented
jenkins

2024-02-20 19:08 UTC, cuichenx commented
jenkins

2024-02-21 00:19 UTC, HeyyyyyyG approved these changes

2024-02-21 00:23 UTC, HeyyyyyyG commented
jenkins