Add Gemma Support and Conversion Scripts
NVIDIA/NeMo pull request #8468
Opened 2024-02-21 04:43 UTC by yaoyu-33

# What does this PR do ?

Add Gemma Support and Conversion Scripts

**Collection**: [NLP]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-02-21 18:15 UTC, yaoyu-33 commented
jenkins

2024-02-21 20:02 UTC, cuichenx requested changes
could you update the config file?

2024-02-21 22:57 UTC, cuichenx approved these changes
LGTM!

2024-02-22 06:27 UTC, yaoyu-33 commented
jenkins

2024-02-22 17:57 UTC, ericharper commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> +        return embeddings * (self.config.hidden_size ** 0.5)
also could you add a docstring explaining why we have this class?

2024-02-22 18:07 UTC, yaoyu-33 commented on nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py
> +        return embeddings * (self.config.hidden_size ** 0.5)
Yes, I think only 0.5 makes sense for now. It means sqrt(hidden_dim)
I will add a docstring to it!

2024-02-22 18:14 UTC, yaoyu-33 commented
jenkins

2024-02-26 18:17 UTC, yaoyu-33 commented
jenkins

2024-02-26 18:24 UTC, cuichenx approved these changes

2024-02-26 22:18 UTC, yaoyu-33 commented
jenkins

2024-02-27 00:50 UTC, yaoyu-33 commented
jenkins

2024-02-27 17:43 UTC, merged