Tutorial on Lhotse Dataloading for ASR fine-tuning
NVIDIA/NeMo pull request #8510
Opened 2024-02-26 19:05 UTC by pzelasko

# What does this PR do ?

Tutorial on Lhotse Dataloading for ASR fine-tuning

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Tutorial on Lhotse Dataloading for ASR fine-tuning

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [x] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-02-26 19:29 UTC, pzelasko commented
jenkins

2024-02-26 20:14 UTC, pzelasko commented
jenkins

2024-02-27 15:05 UTC, pzelasko commented
jenkins

2024-02-28 00:54 UTC, erastorgueva-nv requested changes
Submitted my comments so far, have only reviewed the beginning

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "![image](https://raw.githubusercontent.com/lhotse-speech/lhotse/master/docs/logo.png)\n",
logo shows up as very large when I view it here (https://github.com/NVIDIA/NeMo/blob/lhotse-dataloading-tutorial/tutorials/asr/Lhotse_Dataloading.ipynb), please make it smaller. I think you will have to use HTML tags

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "In this tutorial we introduce the integration of NeMo with Lhotse, a library for speech data preparation and loading. Lhotse adds new capabilities to NeMo, allowing to move certain operations su
add a hyperlink for Lhotse in case people want to learn more about it

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "Lhotse represents speech data as python objects, and provides efficient sampling and dataloading mechanisms. The core Lhotse concepts leveraged in NeMo integration are:\n",
python -> Python
in NeMo integration -> in the NeMo integration

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "- Representation for a dataset and/or mini-batch: [CutSet](https://lhotse.readthedocs.io/en/latest/api.html#lhotse.cut.CutSet).\n",
I think maybe "Representations of individual examples", "Representations of datasets and/or mini-batches"

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "Like NeMo, Lhotse leverages JSON Lines (JSONL) format to keep metadata in manifests. Unlike NeMo, Lhotse's manifests are mapped into Python objects. Most data represented by NeMo manifests are a
"leverages the JSON Lines (JSONL) file format"
"are a special case of the kind of data supported by Lhotse" maybe?
"enabled by the LazyNeMoIterator..."

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "Building a `DataLoader` with Lhotse relies heavily on `CutSampler` to sample a mini-batch on metadata level as a `CutSet`, which is then passed to a map-style PyTorch dataset that converts the `
"relies heavily on". Unclear what information "heavily" is conveying here. Maybe "...with Lhotse requires using CutSampler..."

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "- Tutorial on Lhotse Shar format (\"tarred\" data format in Lhotse): [![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lhotse-speech/l
the buttons are off-center. I wonder if there is an easy fix to shift them downwards so they look centered with the text

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "The dataloader is being constructed in NeMo from a dataset configuration using function [get_lhotse_dataloader_from_config](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/common/data/
"using the function"

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "For the sake of the tutorial, we'll be using very small datasets to keep things quick. The first example is mini LibriSpeech, a 5h train set and 2h dev set collection that was released alongside
"sake" -> "purposes" (less casual)
"we'll" -> "we will" (makes the text flow better I think)
for mini Librispeech, add OpenSLR link?
"archive with the data"
"prepare" -> "preparation", or even better "download" -> `download_librispeech`, "prepare" -> `prepare_librispeech`

2024-02-28 00:54 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "        .from_manifests(**libri[split])\n",
it's not obvious why `**libri[split]` works, is there a simple way to explain it, maybe in the code comments?
maybe doesn't matter too much if it's just a "how-to"

2024-02-29 19:10 UTC, erastorgueva-nv requested changes
Looks great! Just minor grammar fixes

2024-02-29 19:10 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "We'll cover NeMo native tarred format below. If you're interested in Lhotse Shar tarred format, these also work in NeMo -- [please visit the **relevant Lhotse Shar tutorial** for details](https:
"the NeMo native..."
"in the Lhotse Shar ..."
"--" -> "—"

2024-02-29 19:10 UTC, erastorgueva-nv commented on tutorials/asr/Lhotse_Dataloading.ipynb
> +    "- The only other modification is that we're adding `trainer.train_limit_batches` option which tells the trainer what's the size of a pseudo-epoch. In previous examples we could have measured tra
"--" -> "—"

2024-03-23 01:43 UTC, closed without merging