Added NeMo Guardrails paper
NVIDIA/NeMo pull request #8940
Opened 2024-04-16 12:55 UTC by trebedea

# What does this PR do ?

Added NeMo Guardrails paper to publications.

**Collection**: NLP

# Changelog 
- Added NeMo Guardrails paper to publications.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Jenkins CI
To run Jenkins, a NeMo User with write access must comment `jenkins` on the PR.

# Before your PR is "Ready for review"
**Pre checks**:
- [X] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [X] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-04-16 13:02 UTC, cparisien approved these changes

2024-04-16 22:56 UTC, erastorgueva-nv requested changes
Thanks, formatting is good, please just apply the fix requested by the DCO bot here: https://github.com/NVIDIA/NeMo/pull/8940/checks?check_run_id=23877635382.

2024-04-17 09:48 UTC, trebedea commented
Thank you @erastorgueva-nv ! 
In NeMo Guardrails we have GPG signing or sign-off (first is preferred over the second, if possible). I thought that NeMo also accepts GPG.

2024-04-17 11:33 UTC, titu1994 commented
In NeMo GitHub we have only signoff. We can look into gpg later

2024-04-17 17:18 UTC, erastorgueva-nv approved these changes

2024-04-17 17:19 UTC, merged