Add video neva TRT export
NVIDIA/NeMo pull request #9256
Opened 2024-05-20 17:14 UTC by meatybobby

# What does this PR do ?

Add video neva TRT export

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-06-27 17:46 UTC, oyilmaz-nvidia requested changes
We'll likely need to reorg the code later in another PR. But let's make these two minor changes and then we need to discuss this in a bit more detail later.

2024-06-27 17:46 UTC, oyilmaz-nvidia commented on nemo/export/multimodal_exporter.py
> +# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
Can we change the filename to tensort_rt_mm_exporter.py please?

2024-06-27 17:46 UTC, oyilmaz-nvidia commented on nemo/export/multimodal_exporter.py
> +class MultimodalExporter(ITritonDeployable):
Can we please change class name to TensorRTMMExporter?

2024-06-27 23:47 UTC, pablo-garay commented
CI passed (test that failed flaky & is now fixed): https://github.com/NVIDIA/NeMo/actions/runs/9702892079/job/26779932157

2024-06-28 23:37 UTC, oyilmaz-nvidia approved these changes
LGTM.

2024-06-28 23:37 UTC, merged