TRT-LLM Export Code Cleanup
NVIDIA/NeMo pull request #9270
Opened 2024-05-21 21:03 UTC by oyilmaz-nvidia

# What does this PR do ?

Cleaning all of the unused functions, classes, etc, after the TRT-LLM API integration.

2024-05-22 14:11 UTC, janekl submitted a review, later dismissed

2024-05-22 17:33 UTC, jiemingz commented
[get_tensor_parallel_group](https://github.com/oyilmaz-nvidia/NeMo/blob/export-cleanup/nemo/export/trt_llm/tensor_utils.py#L47C5-L47C30) is not used anymore.

2024-05-22 17:41 UTC, jiemingz commented
I believe [cpu_map_location] (https://github.com/oyilmaz-nvidia/NeMo/blob/export-cleanup/nemo/export/trt_llm/utils.py#L63)
is duplicated with [this](https://github.com/oyilmaz-nvidia/NeMo/blob/export-cleanup/nemo/export/trt_llm/nemo/convert.py#L26) 

Also it seems to be `cpu_map_location` and `gpu_map_location` should be in `trt_llm/nemo/nemo.py` since thats where they're only used

2024-05-22 17:43 UTC, jiemingz commented
[This function ](https://github.com/oyilmaz-nvidia/NeMo/blob/export-cleanup/nemo/export/trt_llm/nemo/convert.py#L418) is only used by `build` and `refit` so it can be removed, eventually though we'll have to add it back as well when `build` and `refit` are moved onto the new API

2024-05-22 17:49 UTC, jiemingz requested changes
Please check my comments above @oyilmaz-nvidia, thanks!

2024-05-22 18:33 UTC, oyilmaz-nvidia commented
Thanks @jiemingz for your review. Updating the code per your comments.

2024-05-30 18:05 UTC, jiemingz approved these changes

2024-05-30 19:04 UTC, meatybobby approved these changes

2024-05-30 19:26 UTC, merged