Nemo ux/llm factories
NVIDIA/NeMo pull request #9720
Opened 2024-07-12 13:50 UTC by marcromeyn

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

**Collection**: [Note which collection this PR will affect]

# Changelog 
- Add specific line by line info of high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-07-19 03:43 UTC, akoumpa commented on nemo/collections/llm/api.py
> -
if that's a git move can we drop the line removal?

2024-07-19 03:44 UTC, akoumpa commented on nemo/collections/llm/models/llama3_8b_64k.py
> +        expert_model_parallel_size=1,
is this line needed?

2024-07-19 03:47 UTC, akoumpa requested changes
Can we rename the directory `models` to `recipes`?

Otherwise it's confusing why there's a mistral.py under both `collections/llm/gpt/model` and `collections/llm/models`. 
I don't have any strong preference as long as one of the two directories changes name.

2024-07-20 00:15 UTC, ashors1 commented on nemo/collections/llm/models/llama3_8b_64k.py
> +        expert_model_parallel_size=1,
No, I removed it

2024-07-20 00:15 UTC, ashors1 commented
> Can we rename the directory `models` to `recipes`?
> 
> Otherwise it's confusing why there's a mistral.py under both `collections/llm/gpt/model` and `collections/llm/models`. I don't have any strong preference as long as one of the two directories changes name.

Done

2024-07-23 16:10 UTC, akoumpa approved these changes

2024-07-23 16:14 UTC, merged