Add SpeechLLM docs
NVIDIA/NeMo pull request #9780
Opened 2024-07-17 23:23 UTC by stevehuang52

# What does this PR do ?

Add docs to SpeechLLM

**Collection**: [multimodal]

2024-07-18 17:10 UTC, zhehuaichen submitted a review, later dismissed
Great work! Thank you so much!

2024-07-18 17:16 UTC, stevehuang52 commented on docs/source/multimodal/speech_llm/configs.rst
> +    train_ds:
I added links to lhotse dataset in the dataset.rst, but please feel free to update configs.rst as well, either way is fine with me~

2024-07-18 21:00 UTC, zhehuaichen commented on docs/source/multimodal/speech_llm/configs.rst
> +    train_ds:
added

2024-07-23 15:44 UTC, zhehuaichen submitted a review, later dismissed

2024-07-23 17:15 UTC, titu1994 requested changes
Requires images to be moved to GH release, rest all are minor comments

2024-07-23 17:15 UTC, titu1994 commented on docs/source/multimodal/speech_llm/images/bestow.png
Don't add images to git. Upload file to last release, and put url in rst

2024-07-23 17:15 UTC, titu1994 commented on docs/source/multimodal/speech_llm/images/salm.png
Same here

2024-07-23 19:02 UTC, stevehuang52 commented on docs/source/multimodal/speech_llm/configs.rst
> +      save_top_k: 5
LLM weights are not saved when using LoRA

2024-07-23 19:05 UTC, stevehuang52 commented on docs/source/multimodal/speech_llm/datasets.rst
> +------------------------------
fixed

2024-07-23 19:06 UTC, stevehuang52 commented on docs/source/multimodal/speech_llm/datasets.rst
> +In order to use a context file, you can set `++model.data.train_ds.context_file=<path to to context file>` in the command line or use multiple context files with `++model.data.train_ds.context_file=[
each dataset can have it's own list of context files, such that ASR and ASR can sample from each pool separately

2024-07-23 19:11 UTC, merged