CUDA Memory Profile Analyzer
NVIDIA/NeMo pull request #9860
Opened 2024-07-24 05:36 UTC by tonyjie

# What does this PR do ?
- Collect CUDA memory snapshot based on the previous commit (#9096 ), and further analyze which parts of the model contribute to the total memory footprint. 
- The memory profile will generate two `pickle file`, one for weight, one for activation. The user can load the file in the below page: https://pytorch.org/memory_viz
- If out-of-memory (CUDA OOM) occurs, the tool will capture the snapshot before OOM occurs, and generate the `pickle file`.
- With knobs `analysis_enabled: True`, the memory profile analyzer will generate two csv files each for weight/activation/OOM. The output csv files includes:
  1. Weight
      - `alive_memory_weight.csv`
      - `group_by_alloc_frames_weight.csv`
  2. Activation
      - `alive_memory_memory.csv`
      - `group_by_alloc_frames_memory.csv`
  3. OOM
      - `alive_memory_oom.csv`
      - `group_by_alloc_frames_oom.csv`

# Changelog 
- Fix some issues of previous memory profile
    - `batch_idx` mismatch issue.
    - `max_entries` is too small, which makes the generated snapshot easily truncated.
- Add weight memory capturing.
- Add OOM case support.
- Added the option to enable further analysis to the generated memory snapshot file. The analyzer finds the peak memory of the snapshot, and generate two csv files, including
    1. All the alive memory buffers at that peak moment
    2. Group them by allocation frames, showing the relationship between model layer and its corresponding memory footprint.

# Usage
- Add the below knobs to the yaml run config.

```python
# Memory Profile
memory_profile:                                                                      
   enabled: true                                                                      
   start_step: 1                                                                      
   end_step: 3                                                                        
   rank: 0                                                                            
   output_path: <path/to/out_file>
   analysis_enabled: true
```

# GitHub Actions CI

The Jenkins CI system has been replaced by GitHub Actions self-hosted runners.

The GitHub Actions CI will run automatically when the "Run CICD" label is added to the PR.
To re-run CI remove and add the label again.
To run CI on an untrusted fork, a NeMo user with write access must first click "Approve and run".

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation?
- [ ] Does the PR affect components that are optional to install? (Ex: Numba, Pynini, Apex etc)
  - [ ] Reviewer: Does the PR have correct import guards for all optional libraries?
  
**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation

If you haven't finished some of the above items you can still open "Draft" PR.

## Who can review?

Anyone in the community is free to review the PR once the checks have passed. 
[Contributor guidelines](https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md) contains specific people who can review PRs to various areas.

# Additional Information
* Related to # (issue)

2024-07-31 21:35 UTC, ericharper commented on nemo/utils/memory_profile_analyzer.py
this file needs a copyright header

2024-08-01 06:21 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +# from nemo.utils.memory_profile_analyzer import peak_memory_analysis_activation, peak_memory_analysis_weight, peak_memory_analysis_oom
is the commented line needed?

2024-08-01 06:24 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                    raise Exception(f"Snapshot file not found: {self._memory_profile_snapshot_file_oom}")
Maybe move this after line 1833 `torch.cuda.memory._dump_snapshot`?

2024-08-01 06:25 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                        if self._memory_profile_analysis_enabled:
do you need this if ? I would assume `_memory_profile_analysis_enabled` does not change value and in line 1880 you already check whether it's true or not.

2024-08-01 06:26 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                                raise Exception(f"Snapshot file not found: {self._memory_profile_snapshot_file_weight}")
same as https://github.com/NVIDIA/NeMo/pull/9860/files#r1699506572

2024-08-01 06:27 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                    if self._real_batch_idx == self._memory_profile_start_step and get_rank() == self._memory_profile_rank:
why is it `self._real_batch_idx == self._memory_profile_start_step ` instead of `self._real_batch_idx >= self._memory_profile_start_step ` ?

2024-08-01 06:27 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                    if self._real_batch_idx == self._memory_profile_end_step and get_rank() == self._memory_profile_rank:
same as https://github.com/NVIDIA/NeMo/pull/9860/files#r1699509060

2024-08-01 06:28 UTC, akoumpa commented on nemo/core/classes/modelPT.py
> +                    if self._memory_profile_analysis_enabled and self._memory_profile_complete:
same as previously, `self._memory_profile_analysis_enabled` should be true? due to line 1890

2024-08-01 06:29 UTC, akoumpa commented on nemo/utils/memory_profile_analyzer.py
> +    after_prune_frames = [prune_frames(x[3]) for x in alive_memory]
what's x[3]?

2024-08-01 06:31 UTC, akoumpa commented on nemo/utils/memory_profile_analyzer.py
> +def compare_alive_memory(tracker, time_us_1, time_us_2):
can you add a couple tests for this?

2024-08-01 06:34 UTC, akoumpa commented on nemo/utils/memory_profile_analyzer.py
> +def alloc_memory_timeline(trace):
if that finds the maximum/min alloc memory and the corresponding timestamps, it would be helpful if that was reflected in the name.

2024-08-01 06:34 UTC, akoumpa commented on nemo/utils/memory_profile_analyzer.py
> +        if (action == "alloc"):
you don't need brackets.

2024-08-01 06:35 UTC, akoumpa commented on nemo/utils/memory_profile_analyzer.py
> +def record_alloc_memory_timeline(trace):
this looks very similar to `alloc_memory_timeline` can you refactor to reduce duplicate code?

2024-08-01 06:37 UTC, akoumpa requested changes
Thanks, just a few minor comments, this looks great overall.

2024-08-01 06:38 UTC, akoumpa commented
One more request @tonyjie , can you rebase to the latest main & use --signoff to your commits and push again ? Otherwise CI won't play.

2024-08-06 23:55 UTC, tonyjie commented
> One more request @tonyjie , can you rebase to the latest main & use --signoff to your commits and push again ? Otherwise CI won't play.

I did that but the CI keeps failing. Is there any issue with that?

2024-08-08 05:52 UTC, akoumpa approved these changes

2024-08-21 17:36 UTC, titu1994 reviewed
Overall looks quite a nice improvement. Minor comments here and there

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +                self._memory_profile_weight_enabled = True  # Set as True
I'm wondering if it's worth making this config configurable. Probably not ?

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +                    torch.cuda.memory._record_memory_history()
Does this need specific version of pytorch ? If so please guard it so that it doesn't run on lower pytorch versions

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +                    torch._C._cuda_attach_out_of_memory_observer(self.oom_observer)
Same as above

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +    def oom_observer(self, device, alloc, device_alloc, device_free, *args, **kwargs):
Maybe make it a private method ? With leading _

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +    def oom_observer(self, device, alloc, device_alloc, device_free, *args, **kwargs):
Plus can we avoid **kwargs for any user facing public methods

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +            torch.cuda.memory._dump_snapshot(f"{self._memory_profile_snapshot_file_oom}")
Guard if necessary

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +        # logging.info(f"Training Real batch {self._real_batch_idx} started.")
Can be removed ?

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +        # logging.info(f"Training Real batch {self._real_batch_idx} ended.")
Remove ?

2024-08-21 17:36 UTC, titu1994 commented on nemo/utils/memory_profile_analyzer.py
> +    Get the printed frames for the alive_memory.
Can you add docstring explaining what is the input

2024-08-21 17:36 UTC, titu1994 commented on nemo/utils/memory_profile_analyzer.py
> +    time_us = timepoint['time_us']
Docstring

2024-08-21 17:36 UTC, titu1994 commented on nemo/core/classes/modelPT.py
> +        self._real_batch_idx = 0
Can this be avoided by instead using self.trainer.global_step instead of trainer is not None (and it's never none during training step call anyway)

2024-10-01 02:04 UTC, closed without merging

2024-10-22 14:28 UTC, pzelasko commented
This PR seems to have slipped through. Should we merge it? @ericharper @titu1994